### ISSUE TITLE
自己定义的声明文件 .d.ts 编译时找不到

### ISSUE THREAD

**Issue by Jonny-china** [dcloudio/uni-app#1048]
**问题描述**
我在uniapp中使用ts写代码，自己定义的声明文件以.d.ts结尾，但是编译时无法找到
![image](https://user-images.githubusercontent.com/31563977/69771641-80304580-11c8-11ea-86cb-bf19e62d4374.png)
![image](https://user-images.githubusercontent.com/31563977/69771661-90482500-11c8-11ea-98f2-e5804c78b6f1.png)

**实际结果**
![image](https://user-images.githubusercontent.com/31563977/69771484-ecf71000-11c7-11ea-8c8a-9482cdfa3719.png)

```bash
ERROR  Failed to compile with 1 errors                                                                                                                                                                                                      上午10:10:24

This dependency was not found:

* @/types/order in ./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-1!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--14-2!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modu
les/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages/order/components/OrderItem/index.vue?vue&type=s
cript&lang=ts&
```

**系统信息:**
 - 发行平台:微信小程序
 - uni-app版本：
   uni-app v2.4.2
   uni-app cli v2.0.0-24220191115006
 - 设备信息  OS: macOS 10.15.1

**补充信息:**
我在引入时加了后缀.d.ts，就报这样的错误
![image](https://user-images.githubusercontent.com/31563977/69771844-1e241000-11c9-11ea-9e77-5c142ff6edd1.png)
![image](https://user-images.githubusercontent.com/31563977/69771864-34ca6700-11c9-11ea-8714-8f40bbfc7ecb.png)
```bash
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                      上午10:20:53

 error  in ./src/types/order.d.ts

Module build failed (from ./node_modules/ts-loader/index.js):
Error: Debug Failure. Output generation failed
    at Object.transpileModule (/Users/jonny/Documents/office/car-owner-applet/node_modules/typescript/lib/typescript.js:116825:29)
    at getTranspilationEmit (/Users/jonny/Documents/office/car-owner-applet/node_modules/ts-loader/dist/index.js:318:74)
    at successLoader (/Users/jonny/Documents/office/car-owner-applet/node_modules/ts-loader/dist/index.js:66:15)
    at Object.loader (/Users/jonny/Documents/office/car-owner-applet/node_modules/ts-loader/dist/index.js:22:12)

 @ ./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-1!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--14-2!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/l
ib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages/order/components/OrderItem/index.vue?vue&type=script&lang=ts& 1
4:14-43
 @ ./src/pages/order/components/OrderItem/index.vue?vue&type=script&lang=ts&
 @ ./src/pages/order/components/OrderItem/index.vue
 @ ./node_modules/babel-loader/lib!./node_modules/ts-loader??ref--14-1!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--14-2!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-custom-block-loader??ref--0-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./src/pages/order/index.vue?vue&type=script&lang=ts&
 @ ./src/pages/order/index.vue?vue&type=script&lang=ts&
 @ ./src/pages/order/index.vue
 @ ./src/main.ts?{"page":"pages%2Forder%2Findex"}
```

**Comment by zhetengbiji** [comment]
如果问题仍然存在，请提供更完整测工程信息
