### ISSUE TITLE
vue-cli 中 yarn upgrade 更新后运行报错

### ISSUE THREAD

**Issue by loewe0202** [dcloudio/uni-app#1238]
**问题描述**
vue-cli 中 yarn upgrade 更新后运行报错

**复现步骤**
1.  vue create -p dcloudio/uni-preset-vue test
2. cd test
3. yarn upgrade
4. yarn dev:mp-weixin

**预期结果**
正常编译

**实际结果**
yarn dev:mp-weixin
yarn run v1.21.1
$ cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch
请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
/Users/loewe0202/Desktop/test/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318
initAutoImportComponents(pagesJsonObj.easycom)
^

TypeError: initAutoImportComponents is not a function
    at Object.<anonymous> (/Users/loewe0202/Desktop/test/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/loewe0202/Desktop/test/node_modules/@dcloudio/vue-cli-plugin-uni/index.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**系统信息:**
 - 发行平台: 微信小程序
yarn run info
yarn run v1.21.1
$ node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js
uni-app v2.5.1
uni-app cli v2.0.0-alpha-25120200103006

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 10.16.3 - /var/folders/7t/ndbrwh2d09vf8pyw988hmncwz_nng3/T/yarn--1578446579605-0.1116661143653408/node
    Yarn: 1.21.1 - /var/folders/7t/ndbrwh2d09vf8pyw988hmncwz_nng3/T/yarn--1578446579605-0.1116661143653408/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 79.0.3945.88
    Firefox: 66.0.5
    Safari: 13.0.4
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-25120200103006 => 2.0.0-alpha-24020191108002
    @dcloudio/uni-h5: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-helper-json: * => 1.0.4
    @dcloudio/uni-migration: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-alipay: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-baidu: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-qq: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-toutiao: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-weixin: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-stat: ^2.0.0-25120200103006 => 2.0.0-25120200103006 (2.0.0-v3-24020191018001)
    @dcloudio/uni-template-compiler: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-25120200103006 => 2.0.0-alpha-25120200103006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-25120200103006 => 2.0.0-alpha-25120200103006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-25120200103006 => 2.0.0-alpha-25120200103006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-25120200103006 => 2.0.0-alpha-25120200103006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.0 => 4.1.2
    @vue/cli-shared-utils:  4.1.2
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: 4.1.1

✨  Done in 14.29s.

**Comment by Rockergmail** [comment]
+1

**Comment by imWayneWY** [comment]
+1

**Comment by ShyZhen** [comment]
+1

**Comment by Wangyaqi** [comment]
这个是新增的功能，自动导入组件，建议新建一个项目对比一下依赖版本


| |
我
|
|
wangyaqi988@163.com
|
签名由网易邮箱大师定制
在2020年1月10日 17:47，litblc<notifications@github.com> 写道：

+1

**Comment by ShyZhen** [comment]
> 这个是新增的功能，自动导入组件，建议新建一个项目对比一下依赖版本 | | 我 | | wangyaqi988@163.com | 签名由网易邮箱大师定制 在2020年1月10日 17:47，litblc<notifications@github.com> 写道： +1 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

反正是解决了我的问题，把那些包全都换成alpha版本了，难顶啊

**Comment by pengleelove** [comment]
`"dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-25120200103006",
    "@dcloudio/uni-h5": "^2.0.0-25120200103006",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-alipay": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-baidu": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-qq": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-weixin": "^2.0.0-25120200103006",
    "@dcloudio/uni-stat": "^2.0.0-25120200103006",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.10",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@dcloudio/uni-cli-shared": "^2.0.0-25120200103006",
    "@dcloudio/uni-migration": "^2.0.0-25120200103006",
    "@dcloudio/uni-template-compiler": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-25120200103006",
    "@types/html5plus": "*",
    "@types/uni-app": "*",
    "@vue/cli-plugin-babel": "3.5.1",
    "@vue/cli-service": "^4.1.0",
    "babel-plugin-import": "^1.11.0",
    "mini-types": "*",
    "miniprogram-api-typings": "^2.8.0-2",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.10"
  },
`

**Comment by pengleelove** [comment]
```
"dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-25120200103006",
    "@dcloudio/uni-h5": "^2.0.0-25120200103006",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-alipay": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-baidu": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-qq": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-25120200103006",
    "@dcloudio/uni-mp-weixin": "^2.0.0-25120200103006",
    "@dcloudio/uni-stat": "^2.0.0-25120200103006",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.10",
    "vuex": "^3.0.1"
  },
  "devDependencies": {
    "@dcloudio/uni-cli-shared": "^2.0.0-25120200103006",
    "@dcloudio/uni-migration": "^2.0.0-25120200103006",
    "@dcloudio/uni-template-compiler": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-25120200103006",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-25120200103006",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-25120200103006",
    "@types/html5plus": "*",
    "@types/uni-app": "*",
    "@vue/cli-plugin-babel": "3.5.1",
    "@vue/cli-service": "^4.1.0",
    "babel-plugin-import": "^1.11.0",
    "mini-types": "*",
    "miniprogram-api-typings": "^2.8.0-2",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.10"
  },

```
