### ISSUE TITLE
编译到微信小程序开发模式时：No matching use for foo.js

### ISSUE THREAD

**Issue by smoothdvd** [dcloudio/uni-app#1269]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

ERROR  Error: No matching use for foo.js

**复现步骤**
[复现问题的步骤]
1.  执行yarn dev:mp-weixin

**预期结果**
正常编译

**实际结果**
```
yarn run v1.21.1
$ cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch
请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布

⠋  开始编译当前项目至 mp-weixin 平台... ERROR  Error: No matching use for foo.js
Error: No matching use for foo.js
    at updateJsLoader (/Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:58:13)
    at /Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:162:5
    at webpackRawConfigFns.forEach.fn (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/lib/Service.js:255:21)
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/lib/Service.js:252:30)
    at PluginAPI.resolveWebpackConfig (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at module.exports (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/lib/commands/build/resolveAppConfig.js:39:25)
    at getWebpackConfig (/Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/commands/build.js:49:88)
    at getWebpackConfigs (/Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/commands/build.js:75:13)
    at build (/Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/commands/build.js:112:26)
    at api.registerCommand (/Users/alexgao/Dev/dogface-mpvue/node_modules/@dcloudio/vue-cli-plugin-uni/commands/build.js:40:11)
    at Service.run (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/lib/Service.js:234:12)
    at Object.<anonymous> (/Users/alexgao/Dev/dogface-mpvue/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**系统信息:**
```
uni-app v2.5.1
uni-app cli v2.0.0-25120200103006

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 79.0.3945.117
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-h5: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-helper-json: * => 1.0.5 
    @dcloudio/uni-mp-alipay: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-baidu: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-qq: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-toutiao: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-weixin: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-stat: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/uni-template-compiler: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-22420190823018 => 2.0.0-25120200103006 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.1.2 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.2 
    @vue/cli-plugin-babel: ^4.0.3 => 4.1.2 
    @vue/cli-plugin-eslint: ^4.0.3 => 4.1.2 
    @vue/cli-plugin-router:  4.1.2 
    @vue/cli-plugin-vuex:  4.1.2 
    @vue/cli-service: ^4.0.3 => 4.1.2 
    @vue/cli-shared-utils:  4.1.2 
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/eslint-config-airbnb: ^4.0.0 => 4.0.1 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.2.3 => 5.2.3 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.10 => 2.6.11 
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.8.3 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by Wangyaqi** [comment]
可以上传一份精简之后的项目上来我们验证一下

**Comment by smoothdvd** [comment]
@Wangyaqi 升级到Vue 2.6.11就会报这个错误。uni-app版本为2.0.0-25120200103006。

**Comment by lmf** [comment]
这个问题前两天有人提过的，不是说是框架bug吗，升级到alpha版就可以了，几天过去了也没见发新版本

**Comment by smoothdvd** [comment]
@lmf 不急，等正式版。

**Comment by xuwenkeke** [comment]
同样碰到此问题, 希望尽快修复

**Comment by kingport** [comment]
同样遇到这样的问题有 升级了也不行 还有其他解决方案吗

**Comment by smoothdvd** [comment]
最新的两个版本升级后都没有问题
