### ISSUE TITLE
android打包 安装:  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;

### ISSUE THREAD

**Issue by Ling1992** [dcloudio/uni-app#1343]
**问题描述**
用android studio 调试失败

然后打包成apk， 在手机里安装后无法运行
logcat提示：
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bun/miitmdid/core/JLibrary;
        at io.dcloud.application.DCloudApplication.onCreate(DCloudApplication.java:70)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1195)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7193)
        at android.app.ActivityThread.access$2200(ActivityThread.java:296)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2208)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:213)

**系统信息:**
 - 发行平台: 安卓
 - 操作系统: android10 
 - HBuilderX版本 2.6.0
 - 设备信息 华为mate30
 - Android-SDK@2.4.2.71156_20191115

**补充信息**
在android9 的华为手机上可以正常运行

**Comment by lxftc6534** [comment]
楼主问题解决了吗？我也遇到相同问题

**Comment by Ling1992** [comment]
> 楼主问题解决了吗？我也遇到相同问题

升级最新的离线打包sdk就可以了
