### ISSUE TITLE
cli构建方式， 微信小程序需要自定义测试环境：

### ISSUE THREAD

**Issue by JimmyZDD** [dcloudio/uni-app#1368]
**问题描述**

cli构建方式， 微信小程序需要自定义测试环境：

**复现步骤**
[复现问题的步骤]
1.  增加脚本
"test:mp-weixin": "cross-env NODE_ENV=test UNI_PLATFORM=mp-weixin vue-cli-service uni-serve --watch"
2. 点击 
 'yarn test:mp-weixin'
3. 查看
```
 ERROR  WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.mode should be one of these:
   "development" | "production" | "none"
   -> Enable production optimizations or development hints.
    at webpack (/Users/jimmy/MiniProjects/uni-cli-ts/node_modules/webpack/lib/webpack.js:31:9)
    at serve (/Users/jimmy/MiniProjects/uni-cli-ts/node_modules/@dcloudio/vue-cli-plugin-uni/commands/serve.js:135:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [2.6.1.20200226]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
```
> uni-cli-ts@0.1.0 info /Users/jimmy/MiniProjects/uni-cli-ts
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v2.6.1
uni-app cli v2.0.0-26120200226001

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 13.2.0 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.122
    Firefox: 72.0.1
    Safari: 13.0.4
  npmPackages:
    @dcloudio/types: * => 0.4.4 
    @dcloudio/uni-app-plus: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-h5: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-helper-json: * => 1.0.5 
    @dcloudio/uni-migration: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-alipay: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-baidu: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-qq: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-weixin: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-stat: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-template-compiler: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-typescript: ^3.5.1 => 3.12.1 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ^4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  3.12.1 
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.3)
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.0 (15.9.0)
    vue-property-decorator: ^8.0.0 => 8.4.0 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: 4.1.2
```

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by xz491839007** [comment]
同样问题，现在使用mode 命令也不行
