### ISSUE TITLE
编译报错TypeError: hasModule is not a function

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#142]
### 依赖版本
![image](https://user-images.githubusercontent.com/30344590/50722053-5bd8ff80-1104-11e9-96ee-a378239037fe.png)
### 详细报错内容
```
-  开始编译当前项目至 mp-weixin 平台...
 ERROR  TypeError: hasModule is not a function
TypeError: hasModule is not a function
    at updateForkTsCheckerWebpackPlugin (E:\project\正大无人货架\univue\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:182:7)
    at api.configureWebpack.webpackConfig (E:\project\正大无人货架\univue\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:252:5)
    at webpackRawConfigFns.forEach.fn (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\lib\Service.js:240:21)
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\lib\Service.js:237:30)
    at PluginAPI.resolveWebpackConfig (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\lib\PluginAPI.js:115:25)
    at module.exports (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:36:25)
    at build (E:\project\正大无人货架\univue\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:65:87)
    at api.registerCommand (E:\project\正大无人货架\univue\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:38:9)
    at Service.run (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\lib\Service.js:219:12)
    at Object.<anonymous> (E:\project\正大无人货架\univue\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! univue@0.1.0 dev:mp-weixin: `cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the univue@0.1.0 dev:mp-weixin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
### 定位到@dcloudio/uni-cli-shared/lib/index.js
exports里面确实没有hasModule这个方法

**Comment by fxy060608** [comment]
更新升级@dcloudio/uni-cli-shared至最新版本（目前为0.1.9）

**Comment by ranwawa** [comment]
> 提供下 `@dcloudio/vue-cli-plugin-uni` 以及 `@dcloudio/uni-cli-shared` 的版本号

之前的版本已经删除,重新安装了.所以看不到啦...就是版本问题
