### ISSUE TITLE
是否支持在.vue文件中的style标签中通过设置lang='scss'来进行scss样式的编写？

### ISSUE THREAD

**Issue by luvletterldl** [dcloudio/uni-app#1544]
**问题描述**
是否支持在.vue文件中的style标签中通过设置lang='scss'来进行scss样式的编写？

**复现步骤**
```
<template>
	<view class="content">
		<image class="logo" src="../../static/logo.png"></image>
		<view>
			<text class="title">{{title}}</text>
		</view>
	</view>
</template>

<script lang="ts">
	import Vue from 'vue';
	export default Vue.extend({
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {

		}
	});
</script>

<style lang="scss">
	.content {
		text-align: center;
		height: 400upx;
	}

	.logo {
		height: 200upx;
		width: 200upx;
		margin-top: 200upx;
	}

	.title {
		font-size: 36upx;
		color: #8f8f94;
	}
</style>
```

**预期结果**
页面可以像不加`lang='scss'`那种正常运行

**实际结果**
```
18:46:29.810 Type checking in progress...
18:46:29.814 Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
18:46:29.815 Error: Missing binding /Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/node-sass/vendor/darwin-x64-57/binding.node
18:46:29.821 Node Sass could not find a binding for your current environment: OS X 64-bit with Node.js 8.x
18:46:29.823 Found bindings for the following environments:
18:46:29.835   - OS X 64-bit with Node.js 12.x
18:46:29.835 This usually happens because your environment has changed since running `npm install`.
18:46:29.852 Run `npm rebuild node-sass` to download the binding for your current environment.
18:46:29.853     at module.exports (/Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/node-sass/lib/binding.js:15:13)
18:46:29.869     at Object.<anonymous> (/Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/node-sass/lib/index.js:14:35)
18:46:29.884     at Module._compile (module.js:652:30)
18:46:29.884     at Object.Module._extensions..js (module.js:663:10)
18:46:29.901     at Module.load (module.js:565:32)
18:46:29.902     at tryModuleLoad (module.js:505:12)
18:46:29.917     at Function.Module._load (module.js:497:3)
18:46:29.918     at Module.require (module.js:596:17)
18:46:29.934     at require (internal/module.js:11:18)
18:46:29.935     at getDefaultSassImplementation (/Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/sass-loader/dist/getDefaultSassImplementation.js:24:10)
18:46:29.951     at getSassImplementation (/Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/sass-loader/dist/getSassImplementation.js:19:72)
18:46:29.952     at Object.loader (/Users/lidongliang/Documents/codes/xiaogua-clock-uni/node_modules/sass-loader/dist/index.js:40:61)
18:46:30.348 No type errors found
18:46:30.353 Version: typescript 3.8.3
18:46:30.353 Time: 826ms
```

我不想根据官网那样的描述在外面重写写一个xxx.scss文件，可不可以像我上面说明的这样来进行开发，我按照官网介绍的方法来进行scss插件安装，但是还是有问题

**Comment by zhetengbiji** [comment]
支持，HBuilderX的话，装一下sass插件

**Comment by luvletterldl** [comment]
目前我看到网上有一种[解决方法](https://blog.csdn.net/eadio/article/details/87284921),官方可否出一个解决方案

**Comment by zhetengbiji** [comment]
> 目前我看到网上有一种[解决方法](https://blog.csdn.net/eadio/article/details/87284921),官方可否出一个解决方案

你是说你插件一直安装失败吗？

**Comment by luvletterldl** [comment]
@zhetengbiji 我在HBuilderX中装了这个sass插件，并不能，还是会报错，具体的可以看一下issue具体的

**Comment by luvletterldl** [comment]
> > 目前我看到网上有一种[解决方法](https://blog.csdn.net/eadio/article/details/87284921),官方可否出一个解决方案
> 
> 你是说你插件一直安装失败吗？

安装成功了，但是页面还是会有报错，是不是我的node版本太高了，我用的最新的LST node 12.16.2

**Comment by zhetengbiji** [comment]
> > > 目前我看到网上有一种[解决方法](https://blog.csdn.net/eadio/article/details/87284921),官方可否出一个解决方案
> > 
> > 
> > 你是说你插件一直安装失败吗？
> 
> 安装成功了，但是页面还是会有报错，是不是我的node版本太高了，我用的最新的LST node 12.16.2

怎么安装的？是从HBuilderX中安装的吗？如果是的话仍然遇到问题，尝试重新安装或者重启。

**Comment by luvletterldl** [comment]
我最终是重启了HBuilderX然后手动在目录下安装了sass-loader，`npm i sass-loader -D`解决了这个问题，希望官方在HBuilderX这个编辑器上多做改善
