### ISSUE TITLE
运行到小程序模拟器微信开发者工具报错

### ISSUE THREAD

**Issue by wengjq** [dcloudio/uni-app#1797]
**问题描述**
运行到小程序模拟器微信开发者工具报错

**复现步骤**
[复现问题的步骤]
1.  新建 uni-app 项目默认模板
2. 点击  '运行'，运行到小程序模拟器，微信小程序
3. 查看
类似问题：https://ask.dcloud.net.cn/question/97571
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
```
15:46:26.377 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
15:46:26.377 小程序各家浏览器内核及自定义组件实现机制存在差异，可能存在样式布局兼容问题，参考：https://uniapp.dcloud.io/matter?id=mp
15:46:26.383 正在编译中...
15:47:12.750  ERROR  Error: No module factory available for dependency type: CssDependency
15:47:12.751 Error: No module factory available for dependency type: CssDependency
15:47:12.751     at addDependency (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:694:12)
15:47:12.752     at iterationOfArrayCallback (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:194:3)
15:47:12.752     at addDependenciesBlock (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:712:5)
15:47:12.753     at Compilation.processModuleDependencies (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:723:4)
15:47:12.756     at afterBuild (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:855:15)
15:47:12.757     at buildModule.err (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:899:11)
15:47:12.758     at callback (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:628:5)
15:47:12.759     at module.build.error (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\Compilation.js:676:12)
15:47:12.759     at handleParseResult (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\NormalModule.js:456:12)
15:47:12.759     at doBuild.err (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\NormalModule.js:478:6)
15:47:12.760     at runLoaders (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\webpack\lib\NormalModule.js:342:12)
15:47:12.764     at d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:373:3
15:47:12.764     at iterateNormalLoaders (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
15:47:12.765     at d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:186:6
15:47:12.766     at context.callback (d:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
15:47:12.767     at childCompiler.runAsChild (D:\Documents\Downloads\HBuilderX\plugins\uniapp-cli\node_modules\mini-css-extract-plugin\dist\loader.js:199:12)
15:48:33.089 已停止运行...

```

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统:win10
 - HBuilderX版本:2.7.9.20200527
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
试一下重新下载HBuilderX整包看还有没有这个问题

**Comment by wengjq** [comment]
@Wangyaqi 
下载整个包是可以了，标准版自己安装的依赖不行。
猜测原因：https://github.com/vuejs/vue-cli/issues/5022

**Comment by NinesunLuang** [comment]
我尝试过有效的解决方法，就是将HBuilderx的安装路径放到根路径上，即可正常。我猜是路径上有中文的目录的原因。下载文件直接安装很可能默认在’下载‘这个中文目录下。
