### ISSUE TITLE
uniCloud.callFunction is not a function

### ISSUE THREAD

**Issue by zero7u** [dcloudio/uni-app#1912]
uniCloud模板项目，点击新增一条数据按钮，出现如下提示：
```
{
	"message": "uniCloud.callFunction is not a function",
	"stack": "TypeError: uniCloud.callFunction is not a function\n    at VueComponent.add (webpack-internal:///./node_modules/babel-loader/lib/index.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js?!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader/index.js?!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-uni-app-loader/using-components.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/index.js?!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader/index.js!../../../../../../Users/qcqwyy/HBuilderProjects/oneshop/pages/index/index.vue?vue&type=script&lang=js&:39:16)\n    at click (http://localhost:8081/static/js/pages-index-index.js:161:27)\n    at invokeWithErrorHandling (http://localhost:8081/static/js/chunk-vendors.js:5096:26)\n    at invoker (http://localhost:8081/static/js/chunk-vendors.js:5421:14)\n    at invokeWithErrorHandling (http://localhost:8081/static/js/chunk-vendors.js:5096:26)\n    at HTMLElement.invoker (http://localhost:8081/static/js/chunk-vendors.js:5417:9)\n    at HTMLElement.original._wrapper (http://localhost:8081/static/js/chunk-vendors.js:10299:25)"
}
```
经排查发现，出现上面情况的原因，是下面一行代码：
```
// 只要在main.js里出现union.callFunction，就会导致 union.callFunction 未定义
Vue.prototype.$axios = (url, data) => uniCloud.callFunction({ name: 'url', data })
```
这是设计如此吗？

**Comment by Wangyaqi** [comment]
此问题会在下版修复，目前可以选择在App.vue内挂载此方法

**Comment by zero7u** [comment]
好的，感谢~
