### ISSUE TITLE
【已解决】java.lang.IllegalStateException: ImageLoader must be init with configuration before using

### ISSUE THREAD

**Issue by jp1017** [dcloudio/uni-app#200]
离线打包hello_app，运行闪退

```
java.lang.IllegalStateException: ImageLoader must be init with configuration before using
    at com.nostra13.dcloudimageloader.core.ImageLoader.checkConfiguration(ImageLoader.java:226)
    at com.nostra13.dcloudimageloader.core.ImageLoader.loadImage(ImageLoader.java:188)
    at com.nostra13.dcloudimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:220)
    at com.nostra13.dcloudimageloader.core.ImageLoader.loadImageSync(ImageLoader.java:206)
    at io.dcloud.feature.nativeObj.b.getBitmap(NativeBitmap.java:282)
    at io.dcloud.feature.nativeObj.NativeView.a(NativeView.java:1181)
    at io.dcloud.feature.nativeObj.NativeView$b.a(NativeView.java:1423)
    at io.dcloud.feature.nativeObj.NativeView.a(NativeView.java:1038)
    at io.dcloud.feature.nativeObj.c.a(NativeBitmapMgr.java:828)
    at io.dcloud.feature.nativeObj.c.a(NativeBitmapMgr.java:248)
    at io.dcloud.feature.nativeObj.FeatureImpl.execute(FeatureImpl.java:31)
    at io.dcloud.feature.b.a(FeatureMgr.java:372)
    at io.dcloud.feature.b.processEvent(FeatureMgr.java:140)
    at io.dcloud.common.b.a.dispatchEvent(Core.java:550)
    at io.dcloud.common.b.b.l.processEvent(WindowMgr.java:196)
    at io.dcloud.common.b.b.h.exec(DHWebview.java:192)
    at io.dcloud.common.b.b.h$1.execute(DHWebview.java:138)
    at io.dcloud.common.adapter.util.MessageHandler$1.handleMessage(MessageHandler.java:23)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:159)
    at android.app.ActivityThread.main(ActivityThread.java:6364)
```

**Comment by jp1017** [comment]
已解决, 添加image初始化

```
    @Override
    public void onCoreReady(ICore coreHandler) {
        //加载自定runtime使用的路径
        SDK.initSDK(coreHandler);
        SDK.requestAllFeature();
        ImageLoaderUtil.initImageLoaderL(activity);
    }
```
