### ISSUE TITLE
“参数尾部增加原始事件对象用于复杂表达式内获取额外数据” 报错：params.concat is not a function

### ISSUE THREAD

**Issue by nie55352177** [dcloudio/uni-app#2021]
**问题描述**
20200814版本HBuilder X报错

**复现步骤**
[复现问题的步骤]
1.  触发按钮点击事件
2.  跳转动态URL页面
3. 报错 params.concat is not a function

**预期结果**
正常跳转

**实际结果**

```

MiniProgramError
params.concat is not a function
TypeError: params.concat is not a function
    at http://127.0.0.1:33071/appservice/common/vendor.js:1202:57
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:33071/appservice/common/vendor.js:1176:23
    at Array.forEach (<anonymous>)
    at Je.handleEvent [as __e] (http://127.0.0.1:33071/appservice/common/vendor.js:1166:17)
    at Object.r.safeCallback (http://127.0.0.1:33071/appservice/__dev__/WAService.js:2:1827260)
    at http://127.0.0.1:33071/appservice/__dev__/WAService.js:2:1966938
    at s (http://127.0.0.1:33071/appservice/__dev__/WAService.js:2:1980424)
    at http://127.0.0.1:33071/appservice/__dev__/WAService.js:2:1966863
    at r (http://127.0.0.1:33071/appservice/__dev__/WAService.js:2:1904675)
```

vendor.js
```
eventOpts.forEach(function (eventOpt) {
        var type = eventOpt[0];
        var eventsArray = eventOpt[1];

        var isCustom = type.charAt(0) === CUSTOM;
        type = isCustom ? type.slice(1) : type;
        var isOnce = type.charAt(0) === ONCE;
        type = isOnce ? type.slice(1) : type;

        if (eventsArray && isMatchEventType(eventType, type)) {
          eventsArray.forEach(function (eventArray) {
            var methodName = eventArray[0];
            if (methodName) {
              var handlerCtx = _this.$vm;
              if (handlerCtx.$options.generic) {
                // mp-weixin,mp-toutiao 抽象节点模拟 scoped slots
                handlerCtx = getContextVm(handlerCtx) || handlerCtx;
              }
              if (methodName === '$emit') {
                handlerCtx.$emit.apply(handlerCtx, processEventArgs(_this.$vm, event, eventArray[1], eventArray[2], isCustom, methodName));

                return;
              }
              var handler = handlerCtx[methodName];
              if (!isFn(handler)) {
                throw new Error(" _vm.".concat(methodName, " is not a function"));
              }
              if (isOnce) {
                if (handler.once) {
                  return;
                }
                handler.once = true;
              }
              var params = processEventArgs(_this.$vm, event, eventArray[1], eventArray[2], isCustom, methodName) || [];
              // 参数尾部增加原始事件对象用于复杂表达式内获取额外数据
              // eslint-disable-next-line no-sparse-arrays
              ret.push(handler.apply(handlerCtx, params.concat([,,,,,,,,,, event])));
            }
          });
        }
      });
```

**系统信息:**
 - 发行平台：微信小程序
 - 操作系统：微信开发者工具(windows)
 - HBuilderX版本：2.8.6.20200814
 - uni-app版本
 - 设备信息：微信开发者工具(windows)

**补充信息**

**Comment by zhetengbiji** [comment]
是触发自定义事件的时候吗？

**Comment by ZJH9Rondo** [comment]
> 是触发自定义事件的时候吗？

@zhetengbiji 该改动目前看是考虑场景不充分，出现问题，如下https://github.com/dcloudio/uni-app/issues/2329
