### ISSUE TITLE
微信小程序编译错误，TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by MeetTheBest** [dcloudio/uni-app#2128]
**问题描述**
运行微信小程序时提示编译错误。

`npm run dev:mp-weixin`

```
Module build failed (from ./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js):
TypeError: Cannot read property 'replace' of undefined
    at /Users/meet/projects/meet/projects/remember-me-applet/node_modules/@dcloudio/uni-cli-shared/lib/util.js:57:14
    at cachedFn (/Users/meet/projects/meet/projects/remember-me-applet/node_modules/@dcloudio/uni-cli-shared/lib/util.js:40:33)
    at /Users/meet/projects/meet/projects/remember-me-applet/node_modules/@dcloudio/webpack-uni-mp-loader/lib/script-new.js:103:41
    at async Promise.all (index 1)

 @ ./src/pages/home/index.vue?vue&type=script&lang=js& 1:0-450 1:466-469 1:471-918 1:471-918
 @ ./src/pages/home/index.vue
 @ ./src/main.ts?{"page":"pages%2Fhome%2Findex"}
```

**补充信息**
经过个人排查后，发现出现到组件的导入问题上！！！
```
import ComponentA from '@/components/xxx';
export default {
  components: {
     [ComponentA.name]: ComponentA, // 这样子引入，将出现编译出错（H5方式运行没问题）
    ComponentA,  // 这样子可以正常编译
  }
}
```

**Comment by fxy060608** [comment]
https://ask.dcloud.net.cn/question/107050?notification_id-800023__rf-false__item_id-138893__answer_id-138893__single-TRUE#!answer_138893
