### ISSUE TITLE
cli项目添加eslint后，HbuilderX 无法正确编译

### ISSUE THREAD

**Issue by niphor** [dcloudio/uni-app#2165]
**问题描述**
我在CLI创建的项目里添加了 eslint，但是如果用HbuilderX来打开项目 并选择“运行到小程序模拟器”时回报错，但是直接运行 yarn dev:mp-weixin 时却不会

**复现步骤**
添加的开发依赖
```
"devDependencies": {
    "@vue/cli-plugin-eslint": "^4.5.7",
    "@vue/eslint-config-standard": "^5.1.2",
    "babel-eslint": "^10.1.0",
    "eslint": "^7.10.0",
    "eslint-plugin-import": "^2.22.1",
    "eslint-plugin-node": "^11.1.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "eslint-plugin-vue": "^7.0.1",
    "lint-staged": "^10.4.0",
    "node-sass": "^4.14.1",
    "sass-loader": "^10.0.2",
  }
```

eslintrc.js
```
module.exports = {
  root: true,
  env: {
    node: true,
  },
  extends: [
    'plugin:vue/essential',
    '@vue/standard',
  ],
  parserOptions: {
    parser: 'babel-eslint',
  },
  rules: {
    'no-console': process.env.NODE_ENV === 'production' ? 'off' : 'off',
    'no-debugger': process.env.NODE_ENV === 'production' ? 'off' : 'off',
    'vue/attributes-order': 'error',
    'vue/order-in-components': 'error',
    // 'vue/name-property-casing': ['error', 'kebab-case'],
    // 'vue/component-name-in-template-casing': ['error', 'kebab-case'],
    'vue/require-default-prop': 'off',
    'vue/max-attributes-per-line': [
      2,
      {
        singleline: 3,
        multiline: {
          max: 1,
          allowFirstLine: false,
        },
      },
    ],
    'no-mixed-operators': [
      'error',
      {
        groups: [
          ['+', '-', '*', '/', '%', '**'],
          ['&', '|', '^', '~', '<<', '>>', '>>>'],
          ['==', '!=', '===', '!==', '>', '>=', '<', '<='],
          ['&&', '||'],
          ['in', 'instanceof'],
        ],
        allowSamePrecedence: false,
      },
    ],
    quotes: ['error', 'single', { allowTemplateLiterals: true }],
    'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: false }],
    'comma-dangle': ['error', 'always-multiline'],
  },
  overrides: [
    {
      files: [
        '*.nvue',
      ],
      processor: 'vue/.vue',
    },
    {
      files: [
        '*.vue',
        '*.nvue',
      ],
      rules: {
        indent: 'off',
        'vue/script-indent': [
          'error',
          2,
          {
            baseIndent: 1,
          },
        ],
      },
    },
  ],
  globals: {
    uni: 'readonly',
    plus: 'readonly',
  },
}

```

**预期结果**
编译并运行微信开发工具

**实际结果**
```17:06:10.317 Module build failed (from ./node_modules/eslint-loader/index.js):
17:06:10.317 /Users/niphor/Workspace/miniprogram/node_modules/eslint/lib/cli-engine/cli-engine.js:406
17:06:10.326     } catch {
17:06:10.326             ^
17:06:10.334 SyntaxError: Unexpected token {
17:06:10.336     at createScript (vm.js:80:10)
17:06:10.342     at Object.runInThisContext (vm.js:139:10)
17:06:10.343     at Module._compile (module.js:616:28)
17:06:10.346     at Object.Module._extensions..js (module.js:663:10)
17:06:10.348     at Module.load (module.js:565:32)
17:06:10.352     at tryModuleLoad (module.js:505:12)
17:06:10.353     at Function.Module._load (module.js:497:3)
17:06:10.356     at Module.require (module.js:596:17)
17:06:10.360     at require (internal/module.js:11:18)
17:06:10.360     at Object.<anonymous> (/Users/niphor/Workspace/miniprogram/node_modules/eslint/lib/cli-engine/index.js:3:23)
17:06:10.365     at Module._compile (module.js:652:30)
17:06:10.369     at Object.Module._extensions..js (module.js:663:10)
17:06:10.373     at Module.load (module.js:565:32)
17:06:10.373     at tryModuleLoad (module.js:505:12)
17:06:10.377     at Function.Module._load (module.js:497:3)
17:06:10.377     at Module.require (module.js:596:17)
17:06:10.748  ERROR  Build failed with errors.

```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 MacOS
 - HBuilderX版本 2.8.13
 - uni-app版本 

```
> miniprogram@0.1.0 info /Users/niphor/Workspace/miniprogram
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v2.8.13
uni-app cli v2.0.0-28920200927001

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.19.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.75
    Firefox: Not Found
    Safari: 14.0
  npmPackages:
    @dcloudio/types: * => 2.0.8 
    @dcloudio/uni-app-plus: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-cli-shared: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-h5: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-helper-json: * => 1.0.6 
    @dcloudio/uni-migration: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-360: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-alipay: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-baidu: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-qq: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-vue: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-mp-weixin: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-quickapp-native: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-stat: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-template-compiler: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/uni-ui: ^1.2.5 => 1.2.5 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-28920200927001 => 2.0.0-28920200927001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.5.7 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.7 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.7 
    @vue/cli-plugin-eslint: ^4.5.7 => 4.5.7 
    @vue/cli-plugin-router:  4.5.7 
    @vue/cli-plugin-vuex:  4.5.7 
    @vue/cli-service: ~4.5.0 => 4.5.7 
    @vue/cli-shared-utils:  4.5.7 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0-rc.4 => 3.0.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^7.0.1 => 7.0.1 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.1.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 (16.0.0-beta.8, 15.9.3)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.5.1 
```

**补充信息**
究其原因是因为 执行的eslint包的js文件有的 catch 后面省略了`(e)`,但即便把这些修改正确，编译时还会报其他错误
感觉
1、HBuilderX 并未遵循eslint配置文件，在对整个文件夹进行检查，并且eslintignore文件排除node_modules也不起作用
2、HBuilderX 是否是有自带的node，且版本较为严格，无法执行有些许错误的代码

**Comment by niphor** [comment]
经测试，大概率是因为 内置node和terminal 和 系统安装的node 版本不统一导致的

如果通过 系统安装的node进行项目初始化，因为node版本问题，一些依赖平台版本的插件 如 node-sass 会报版本不一致

最终 通过指定使用系统自带node和 使用 外部终端 解决问题


但  如果单纯选择使用外部终端，HbuilderX 可能仍旧会使用内置node，导致idea等ide与 HbuilderX 混用时出现各种诡异问题。
