### ISSUE TITLE
编译至 H5 平台异常

### ISSUE THREAD

**Issue by xiaoyucoding** [dcloudio/uni-app#2183]
**问题描述**
page.json 中页面的 style 条件编译异常

**复现步骤**

``` json
{
  "path": "detail/detail",
  "style": {
    "usingComponents": {
      "mp-weixin": {
        "txv-video": "plugin://tencentvideo/video"
      }
    },
    "disableScroll": false
  }
},
```

编译到 `mp-weixin` 平台没有问题，但是编译到 `H5` 平台就会报错。

```
Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-uni-app-loader/using-components.js):
TypeError: source.indexOf is not a function
    at D:\ajy\applet\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:252:16
    at Array.forEach (<anonymous>)
    at parseUsingComponents (D:\ajy\applet\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:249:32)
    at generateUsingComponentsCode (D:\ajy\applet\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:267:22)
    at getUsingComponentsCode (D:\ajy\applet\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:316:10)
    at Object.module.exports (D:\ajy\applet\node_modules\@dcloudio\vue-cli-plugin-uni\packages\webpack-uni-app-loader\using-components.js:16g-components.js:16:23)
```

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本
  + uni-app v2.8.13
  + uni-app cli v2.0.0-28920200927001

**Comment by xiaoyucoding** [comment]
配置写错了，没问题了。

**Comment by winston1991** [comment]
亲，哪里配置错了，我的也出现indexOf is not a function   这个错误了
