### ISSUE TITLE
通过 vue-cli 创建 uni-app 项目,报错

### ISSUE THREAD

**Issue by iceycc** [dcloudio/uni-app#2363]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
通过 vue-cli 创建 uni-app 项目。
按照下面改了配置，但是启动报错
```md
修改依赖为指定版本
查看 HBuilderX 对应的 NPM 依赖版本: 打开 NPM版本记录，版本号 2.0.0- 后面是与 HBuilderX 对应的版本号且小版本不会超过9，比如 HBuilderX 2.7.5.20200518 对应的版本号 2.0.0-27520200518001，2.0.0-271420200618 对应的为 2.0.0-27920200618002。

批量修改 package.json 中 uni 相关依赖为指定的版本号（去掉版本号前面 ^）。

对于有变化的依赖进行增删，提示不存指定版本的依赖可以保留原始版本或者删除，运行时提示缺少的依赖自行安装。

```

**复现步骤**
[复现问题的步骤]
1.  启动  npm run serve
2. 点击  控制台报错
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
报错信息
```shell
MacBook-Pro-4:fx_h5 zwwl$ npm run serve

> fx_h5@0.1.0 serve /Users/iceyang/Documents/fx_h5
> npm run dev:h5


> fx_h5@0.1.0 dev:h5 /Users/iceyang/Documents/fx_h5
> cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve

请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
 INFO  Starting development server...
 ERROR  TypeError: Cannot read property 'findIndex' of undefined
TypeError: Cannot read property 'findIndex' of undefined
    at updateJsLoader (/Users/iceyang/Documents/fx_h5/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:56:42)
    at /Users/iceyang/Documents/fx_h5/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:166:5
    at /Users/iceyang/Documents/fx_h5/node_modules/@vue/cli-service/lib/Service.js:255:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (/Users/iceyang/Documents/fx_h5/node_modules/@vue/cli-service/lib/Service.js:252:30)
    at PluginAPI.resolveWebpackConfig (/Users/iceyang/Documents/fx_h5/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/iceyang/Documents/fx_h5/node_modules/@dcloudio/vue-cli-plugin-uni/commands/serve.js:51:31)
    at Service.run (/Users/iceyang/Documents/fx_h5/node_modules/@vue/cli-service/lib/Service.js:234:12)
    at Object.<anonymous> (/Users/iceyang/Documents/fx_h5/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fx_h5@0.1.0 dev:h5: `cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fx_h5@0.1.0 dev:h5 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/iceyang/.npm/_logs/2020-12-22T02_28_39_628Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fx_h5@0.1.0 serve: `npm run dev:h5`
npm ERR! Exit status 1

```

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
改后的配置看下

**Comment by mikexia930** [comment]
app.js错误:
 TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (App.vue?vue&type=script&lang=ts&:3)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (App.vue?c220:1)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (null:1)
    at __webpack_require__ (bootstrap:81)
    at Object.<anonymous> (main.ts:2)
    at Object.<anonymous> (main.ts:6)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)(env: macOS,mp,1.05.2110290; lib: 2.20.2)
(anonymous) @ VM59:5
doWhenAllScriptLoaded @ VM56:1133
scriptLoaded @ VM56:1161
(anonymous) @ VM56:1186
load (async)
(anonymous) @ assubloader.js:1
j @ VM26 WAService.js:2
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ VM56:1205
(anonymous) @ VM56:1211
loadScripts @ assubloader.js:1
async function (async)
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ VM52:1
t.loadScripts @ VM8 asdebug.js:1
r @ VM8 asdebug.js:1
i.emit @ VM8 asdebug.js:1
set @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
load (async)
handleLoadStart @ VM8 asdebug.js:1
(anonymous) @ instanceframe?s=1636439770241:1
VM26 WAService.js:2 TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (App.vue?vue&type=script&lang=ts&:3)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (App.vue?c220:1)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (null:1)
    at __webpack_require__ (bootstrap:81)
    at Object.<anonymous> (main.ts:2)
    at Object.<anonymous> (main.ts:6)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)(env: macOS,mp,1.05.2110290; lib: 2.20.2)
errorReport @ VM26 WAService.js:2
thirdErrorReport @ VM26 WAService.js:2
(anonymous) @ VM26 WAService.js:2
u @ VM26 WAService.js:2
a @ VM26 WAService.js:2
c @ VM8 asdebug.js:1
r @ VM8 asdebug.js:1
window.onerror @ VM19:1
doWhenAllScriptLoaded @ VM56:1133
scriptLoaded @ VM56:1161
(anonymous) @ VM56:1186
error (async)
t.default @ VM19:1
160 @ VM19:1
n @ VM19:1
(anonymous) @ VM19:1
(anonymous) @ VM19:1
VM26 WAService.js:2 TypeError: Cannot read property 'extend' of undefined
    at Object.<anonymous> (App.vue?vue&type=script&lang=ts&:3)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (App.vue?c220:1)
    at __webpack_require__ (bootstrap:81)
    at Module.<anonymous> (null:1)
    at __webpack_require__ (bootstrap:81)
    at Object.<anonymous> (main.ts:2)
    at Object.<anonymous> (main.ts:6)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)(env: macOS,mp,1.05.2110290; lib: 2.20.2)

**Comment by mikexia930** [comment]
微信小程序的报错，什么都没改过
vue-cli4
vue create -p dcloudio/uni-preset-vue

**Comment by mikexia930** [comment]
h5正常范围，小程序白屏并报错，帮忙看看是什么原因呢，报错贴在上面

**Comment by mikexia930** [comment]
换成非ts版本

app.js错误:
 TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (main.js? [sm]:4)
    at Object.<anonymous> (main.js? [sm]:11)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)
    at Array.webpackJsonpCallback [as push] (bootstrap:34)
    at main.js:4
    at p (VM17 WAService.js:2)
    at r (VM17 WAService.js:2)
    at app.js? [sm]:4
    at p (VM17 WAService.js:2)(env: macOS,mp,1.05.2110290; lib: 2.20.2)
(anonymous) @ VM67:5
doWhenAllScriptLoaded @ VM64:1133
scriptLoaded @ VM64:1161
(anonymous) @ VM64:1186
load (async)
(anonymous) @ assubloader.js:1
j @ VM17 WAService.js:2
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ VM64:1205
(anonymous) @ VM64:1211
loadScripts @ assubloader.js:1
async function (async)
loadScripts @ assubloader.js:1
loadAppResourceScripts @ assubloader.js:1
(anonymous) @ VM60:1
t.loadScripts @ VM8 asdebug.js:1
loadAppService @ VM8 asdebug.js:1
messagerCallback @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
f @ VM8 asdebug.js:1
g @ VM8 asdebug.js:1
(anonymous) @ VM8 asdebug.js:1
_ws.onmessage @ VM8 asdebug.js:1
VM17 WAService.js:2 TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (main.js? [sm]:4)
    at Object.<anonymous> (main.js? [sm]:11)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)
    at Array.webpackJsonpCallback [as push] (bootstrap:34)
    at main.js:4
    at p (VM17 WAService.js:2)
    at r (VM17 WAService.js:2)
    at app.js? [sm]:4
    at p (VM17 WAService.js:2)(env: macOS,mp,1.05.2110290; lib: 2.20.2)
errorReport @ VM17 WAService.js:2
thirdErrorReport @ VM17 WAService.js:2
(anonymous) @ VM17 WAService.js:2
u @ VM17 WAService.js:2
a @ VM17 WAService.js:2
c @ VM8 asdebug.js:1
r @ VM8 asdebug.js:1
window.onerror @ VM5:1
doWhenAllScriptLoaded @ VM64:1133
scriptLoaded @ VM64:1161
(anonymous) @ VM64:1186
VM17 WAService.js:2 TypeError: Cannot read property 'config' of undefined
    at Object.<anonymous> (main.js? [sm]:4)
    at Object.<anonymous> (main.js? [sm]:11)
    at __webpack_require__ (bootstrap:81)
    at checkDeferredModules (bootstrap:47)
    at Array.webpackJsonpCallback [as push] (bootstrap:34)
    at main.js:4
    at p (VM17 WAService.js:2)
    at r (VM17 WAService.js:2)
    at app.js? [sm]:4
    at p (VM17 WAService.js:2)(env: macOS,mp,1.05.2110290; lib: 2.20.2)

**Comment by zhetengbiji** [comment]
现已增加版本管理工具，可以免手动管理版本了。

https://www.npmjs.com/package/@dcloudio/uvm
