### ISSUE TITLE
离线包 video 不能播放

### ISSUE THREAD

**Issue by NiBoTe** [dcloudio/uni-app#2491]
D/J4A: J4ALoader: OK: 'android.os.Build$VERSION' loaded
    J4ALoader: OK: 'android.os.Build' loaded
    J4ALoader: OK: 'java.nio.Buffer' loaded
    J4ALoader: OK: 'java.nio.ByteBuffer' loaded
    J4ALoader: OK: 'java.util.ArrayList' loaded
I/J4A: API-Level: 29
D/J4A: J4ALoader: OK: 'android.media.AudioTrack' loaded
    J4ALoader: OK: 'android.media.MediaCodec$BufferInfo' loaded
    J4ALoader: OK: 'android.media.MediaCodec' loaded
    J4ALoader: OK: 'android.media.MediaFormat' loaded
    J4ALoader: OK: 'android.media.PlaybackParams' loaded
D/J4A: J4ALoader: OK: 'android.os.Bundle' loaded
W/System.err: java.lang.ClassNotFoundException: Didn't find class "tv.danmaku.ijk.media.player.misc.IMediaDataSource" on path: DexPathList[[dex file "InMemoryDexFile[cookie=[0, 531274453376]]", zip file "/data/app/com.HBuilder.UniPlugin-TdUCiCbussx8Suz7gyR4yw==/base.apk"],nativeLibraryDirectories=[/data/app/com.HBuilder.UniPlugin-TdUCiCbussx8Suz7gyR4yw==/lib/arm64, /data/app/com.HBuilder.UniPlugin-TdUCiCbussx8Suz7gyR4yw==/base.apk!/lib/arm64-v8a, /system/lib64, /hw_product/lib64, /system/product/lib64, /prets/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at java.lang.Runtime.nativeLoad(Native Method)
        at java.lang.Runtime.nativeLoad(Runtime.java:1115)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1069)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
W/System.err:     at java.lang.System.loadLibrary(System.java:1668)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.loadLibrary(IjkMediaPlayer.java:178)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.U(IjkMediaPlayer.java:190)
        at io.dcloud.media.video.ijkplayer.media.IjkPlayerView._initMediaPlayer(IjkPlayerView.java:327)
        at io.dcloud.media.video.ijkplayer.media.IjkPlayerView.init(IjkPlayerView.java:481)
        at io.dcloud.media.video.ijkplayer.VideoPlayerView.<init>(VideoPlayerView.java:51)
        at io.dcloud.media.video.DHVideoFrameItem.<init>(DHVideoFrameItem.java:62)
        at io.dcloud.media.video.VideoPlayerMgr.createVideoPlayer(VideoPlayerMgr.java:62)
        at io.dcloud.media.MediaFeatureImpl.VideoPlayer(MediaFeatureImpl.java:42)
        at java.lang.reflect.Method.invoke(Native Method)
        at io.dcloud.common.DHInterface.StandardFeature.executeAction(:4)
        at io.dcloud.common.DHInterface.StandardFeature.execute(:1)
        at io.dcloud.h.b.a(:144)
        at io.dcloud.h.b.b(:3)
        at io.dcloud.h.b.processEvent(:144)
        at io.dcloud.f.b.b.dispatchEvent(:22)
        at io.dcloud.common.core.ui.m.processEvent(:2)
        at io.dcloud.common.core.ui.i.exec(:10)
        at io.dcloud.common.core.ui.i$a.execute(:5)
        at io.dcloud.common.adapter.util.MessageHandler$1.handleMessage(:3)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
E/J4A: J4A_FindClass__catchAll: failed
    J4A_FindClass__asGlobalRef__catchAll: failed: tv/danmaku/ijk/media/player/misc/IMediaDataSource
W/System.err: java.lang.reflect.InvocationTargetException
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
        at io.dcloud.common.DHInterface.StandardFeature.executeAction(:4)
        at io.dcloud.common.DHInterface.StandardFeature.execute(:1)
        at io.dcloud.h.b.a(:144)
        at io.dcloud.h.b.b(:3)
        at io.dcloud.h.b.processEvent(:144)
        at io.dcloud.f.b.b.dispatchEvent(:22)
        at io.dcloud.common.core.ui.m.processEvent(:2)
        at io.dcloud.common.core.ui.i.exec(:10)
        at io.dcloud.common.core.ui.i$a.execute(:5)
        at io.dcloud.common.adapter.util.MessageHandler$1.handleMessage(:3)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8347)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
    Caused by: java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/com.HBuilder.UniPlugin-TdUCiCbussx8Suz7gyR4yw==/lib/arm64/libijksdl.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1668)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer$a.loadLibrary(IjkMediaPlayer.java:178)
        at tv.danmaku.ijk.media.player.IjkMediaPlayer.U(IjkMediaPlayer.java:190)
        at io.dcloud.media.video.ijkplayer.media.IjkPlayerView._initMediaPlayer(IjkPlayerView.java:327)
        at io.dcloud.media.video.ijkplayer.media.IjkPlayerView.init(IjkPlayerView.java:481)
        at io.dcloud.media.video.ijkplayer.VideoPlayerView.<init>(VideoPlayerView.java:51)
        at io.dcloud.media.video.DHVideoFrameItem.<init>(DHVideoFrameItem.java:62)
        at io.dcloud.media.video.VideoPlayerMgr.createVideoPlayer(VideoPlayerMgr.java:62)
        at io.dcloud.media.MediaFeatureImpl.VideoPlayer(MediaFeatureImpl.java:42)
    	... 17 more

打开是黑屏

hbuilderX 3.0.5

**Comment by zhetengbiji** [comment]
官方基座测试是否正常，如果官方基座测试正常，离线打包有问题可以加原生交流群问下 892918401

**Comment by StrivingRabbit** [comment]
由于时间过长未回复，此问题关闭
