### ISSUE TITLE
进行自动化测试时调用page.callMethod失败

### ISSUE THREAD

**Issue by VincentGum** [dcloudio/uni-app#2495]
**问题描述**
进行自动化测试的时候，想通过page.callMethod调用页面方法。
但是一直报错，现实page[28] not exists

**复现步骤**
1.  testcase code
  it('testCallMethod', async () => {
        await page.callMethod("onShareAppMessage")
    })
2. 运行结果
 FAIL  src/pages/tabBar/component/component.test.js
  ● pages/tabBar/component/component.nvue › testCallMethod

    Page[11] not exists

      at b.I.onMessage.t (node_modules/@dcloudio/uni-automator/dist/index.js:1:1384)
      at WebSocket.ws.addEventListener.t (node_modules/@dcloudio/uni-automator/dist/index.js:1:820)
      at WebSocket.onMessage (node_modules/@dcloudio/uni-automator/node_modules/ws/lib/event-target.js:132:16)
      at Receiver.receiverOnMessage (node_modules/@dcloudio/uni-automator/node_modules/ws/lib/websocket.js:825:20)
      at Receiver.dataMessage (node_modules/@dcloudio/uni-automator/node_modules/ws/lib/receiver.js:437:14)
      at Receiver.getData (node_modules/@dcloudio/uni-automator/node_modules/ws/lib/receiver.js:367:17)
      at Receiver.startLoop (node_modules/@dcloudio/uni-automator/node_modules/ws/lib/receiver.js:143:22)

**预期结果**
预期应该能成功调用到该方法。

**实际结果**
一直报错说page不存在

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本
     uni-app v3.1.3
     uni-app cli v2.0.0-alpha-31320210219001
 - 设备信息 macOS

**补充信息**
根据目前的分析，该错误信息是通过：
/my-hello-uni-app/node_modules/@dcloudio/uni-mp-weixin/dist/automator.js
文件中
callMethod: function (t) {
        var n,
            r = ((n = {})[e.VM_NOT_EXISTS] = "Page[" + t.pageId + "] not exists", n[e.METHOD_NOT_EXISTS] = "page." + t.method + " not exists", n);
        return new Promise((function (e, n) {
            T(g(t.pageId), t.method, t.args).then((function (t) {
                return e(t)
            })).catch((function (e) {
                n(Error(r[e]))
            }))
        }))
    }
这个方法生成的。

**Comment by StrivingRabbit** [comment]
有这一句吗？
```js
let page
 beforeAll(async () => {
     // 重新reLaunch至首页，并获取首页page对象（其中 program 是uni-automator自动注入的全局对象）
     page = await program.reLaunch('/pages/tabBar/component/component')
     await page.waitFor(1000)
 })
```

**Comment by StrivingRabbit** [comment]
长时间未回复，此问题关闭
