### ISSUE TITLE
vue3 alpha版本无法正常运行

### ISSUE THREAD

**Issue by dnt1996** [dcloudio/uni-app#2902]
uni-app v2.0.0-alpha-32720210917001  
platform mp-weixin
最简单的案例都无法运行, 前景堪忧啊
```vue
<template>
    <view @click="onClick">
        {{foo}}
    </view>
</template>

<script>
    import {ref} from "vue"
    export default {
        setup() {
            const foo = ref(1)
            return {
                foo,
                onClick() {
                    foo.value++
                }
            }
        },
	}
</script>
```
点击后报错
`
VM763 WAService.js:1 thirdScriptError
Cannot read property 'id' of undefined; [Component] Event Handler Error @ pages/index/index#handleEvent
TypeError: Cannot read property 'id' of undefined
    at ReactiveEffect.queueJob [as scheduler] (http://127.0.0.1:53788/appservice/common/vendor.js:4888:17)
    at triggerEffects (http://127.0.0.1:53788/appservice/common/vendor.js:877:24)
    at triggerRefValue (http://127.0.0.1:53788/appservice/common/vendor.js:1678:11)
    at RefImpl.set (http://127.0.0.1:53788/appservice/common/vendor.js:1729:13)
    at Proxy.onClick (http://127.0.0.1:53788/appservice/pages/index/index.js:297:20)
    at http://127.0.0.1:53788/appservice/common/vendor.js:9313:32
    at Array.forEach (<anonymous>)
    at http://127.0.0.1:53788/appservice/common/vendor.js:9275:23
    at Array.forEach (<anonymous>)
    at ve.handleEvent [as __e] (http://127.0.0.1:53788/appservice/common/vendor.js:9266:17)(env: Windows,mp,1.05.2109101; lib: 2.9.2)
`

**Comment by fxy060608** [comment]
使用最新的HBuilderX Alpha，以及cli 分别测试，未重现该问题，电脑为mac
可以再补充详细的测试环境及测试代码

**Comment by dnt1996** [comment]
> 使用最新的HBuilderX Alpha，以及cli 分别测试，未重现该问题，电脑为mac
> 可以再补充详细的测试环境及测试代码
操作系统是windows, node 14, 编译到微信小程序会出现这个bug
https://github.com/dnt1996/uni-app-vue3-test/tree/composition-api-broken

**Comment by fxy060608** [comment]
已修复，可以将版本调整为：2.0.0-alpha-32820210923001
