### ISSUE TITLE
在pages.js里使用require.context，运行报错不存在context方法

### ISSUE THREAD

**Issue by PineSongCN** [dcloudio/uni-app#3066]
**问题描述**
在pages.js里使用require.context，运行报错不存在context方法，请问如何配置注入require.context

**复现步骤**
[复现问题的步骤]
1.   
```
// pages.js
const modulesFiles = require.context('./router/modules', true, /\.js$/);
```
2. 运行
3. 查看

[或者可以直接贴源代码]

**预期结果**

**实际结果**
```
-  开始编译当前项目至 mp-weixin 平台...modulesFiles:e TypeError: require.context is not a function
    at Object.<anonymous> (D:\_web\_work\mini-volunteer\src\pages.js:2:31)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at processPagesJson (D:\_web\_work\mini-volunteer\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:61:27)
    at getPagesJson (D:\_web\_work\mini-volunteer\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:37:10)
    at parseEntry (D:\_web\_work\mini-volunteer\node_modules\@dcloudio\uni-cli-shared\lib\pages.js:223:17)
    at webpackConfig (D:\_web\_work\mini-volunteer\node_modules\@dcloudio\vue-cli-plugin-uni\lib\mp\index.js:155:5)
    at D:\_web\_work\mini-volunteer\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:184:31
    at D:\_web\_work\mini-volunteer\node_modules\@vue\cli-service\lib\Service.js:251:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\_web\_work\mini-volunteer\node_modules\@vue\cli-service\lib\Service.js:248:30)
    at PluginAPI.resolveWebpackConfig (D:\_web\_work\mini-volunteer\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
out
```

**系统信息:**
 - 发行平台: 微信小程序

**补充信息**

**Comment by StrivingRabbit** [comment]
page.js 不会被编译。运行在 nodejs 环境，可以自行实现或者找其他平替方案
