### ISSUE TITLE
vue3 vite-ts 模板增加 vite-plugin-eslint 之后需要额外配置才能正常运行

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#3247]
**问题描述**

vue3 vite-ts 模板增加 vite-plugin-eslint 之后需要额外配置才能正常运行

**复现步骤**

1. `npx degit dcloudio/uni-preset-vue#vite-ts uni-app-vue3-test`
2. `cd uni-app-vue3-test`
3. `npm i -g yarn && yarn add eslint vite-plugin-eslint eslint-plugin-vue @vue/eslint-config-typescript @rushstack/eslint-patch -D`
4. 修改 `vite.config.ts`

```ts
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import eslint from "vite-plugin-eslint";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [uni(), eslint({ fix: true })],
});

```

5. 增加 `.eslintrc.cjs`

```cjs
/* eslint-env node */
require("@rushstack/eslint-patch/modern-module-resolution");

module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:vue/vue3-essential",
    "@vue/eslint-config-typescript",
  ],
};

```

6. `yarn run dev:mp-weixin`

**预期结果**

正常运行不报错。

**实际结果**

报错。

```shell
[plugin:vite:eslint] No files matching 'src/pages.json.js' were found.
at pages.json.js:1:0
```

**补充信息**

如果修改 `vite.config.ts` 如下，仍会报错。

```ts
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import eslint from "vite-plugin-eslint";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    eslint({ exclude: ["node_modules", "./src/pages.json.js"], fix: true }),
  ],
});

```

```shell
[plugin:vite:eslint] No files matching 'src/manifest.json.js' were found.
at manifest.json.js:1:0
```

最后修改 `vite.config.ts` 如下即可正常运行。

```ts
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import eslint from "vite-plugin-eslint";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    eslint({
      exclude: [
        "node_modules",
        "./src/pages.json.js",
        "./src/manifest.json.js",
      ],
      fix: true,
    }),
  ],
});

```

这个处理方法不算优雅，官方能否内部处理下避免这个问题？

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114011

**Comment by ModyQyW** [comment]
请问未来会考虑切成 semver 吗？

**Comment by ModyQyW** [comment]
更新到 3.0.0-alpha-3030820220114011 之后问题依然存在。

**Comment by fxy060608** [comment]
> 更新到 3.0.0-alpha-3030820220114011 之后问题依然存在。

package.json中锁定3.0.0-alpha-3030820220114011 版本

**Comment by ModyQyW** [comment]
糟糕的体验
