### ISSUE TITLE
在hbuilder运行到模拟器上白屏，发现sass-loader报错outputStyle属性不支持

### ISSUE THREAD

**Issue by AK47-dadada** [dcloudio/uni-app#3298]
**问题描述**
在hbuilder运行到模拟器上白屏

**复现步骤**
[复现问题的步骤]
1.  启动 '使用hbuilder运行到mumu模拟器，'
2. 点击  '运行到模拟器'
3. 发现模拟器打开，app打开，但是白屏（tabbar可以正常显示）

[或者可以直接贴源代码]

**预期结果**
可以正常调试

**实际结果**
09:17:51.299 Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js):
09:17:51.310 ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
09:17:51.319  - options has an unknown property 'outputStyle'. These properties are valid:
09:17:51.325    object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter?, nvue? }
09:17:51.332     at validate (D:\Jm-code\uniapp\cowman\u-cowman\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\node_modules\schema-utils\dist\validate.js:96:11)
09:17:51.332     at Object.loader (D:\Jm-code\uniapp\cowman\u-cowman\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\dist\index.js:38:28)
09:17:52.079  DONE  Build complete. Watching for changes...
09:17:52.085 项目 'u-cowman' 编译成功。
09:17:52.093  ERROR  Build failed with errors.
09:17:52.264 正在建立手机连接...
09:17:53.288 手机端调试基座版本号为3.3.11，版本号相同，跳过基座更新
09:17:53.411 正在同步手机端程序文件...
09:18:01.873 同步手机端程序文件完成
09:18:02.282 正在启动HBuilder调试基座
09:18:03.757 应用【MY-APP】已启动...
09:18:05.191 %c uView V2.0.28 %c https://www.uviewui.com/
09:18:05.232 【uni-simple-router 提示】：当前版本 2.0.8-beta.2 此版本为测试版。有BUG请退回正式版，线上正式版本：2.0.7
09:18:05.601 需要登录 at permission.js:21
09:18:05.621 需要登录 at permission.js:21
09:18:05.768 App Launch at App.vue:7
09:18:05.785 App Show at App.vue:10
09:18:06.175 加载完成啦 at router/index.js:68
09:18:06.195 跳转结束 at router/index.js:101
09:18:06.257 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught Error: Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/sass-loader/dist/cjs.js):
09:18:06.278 ValidationError: Invalid options object. Sass Loader has been initialized using an options object that does not match the API schema.
09:18:06.297 - options has an unknown property 'outputStyle'. These properties are valid:
09:18:06.318 object { implementation?, sassOptions?, prependData?, sourceMap?, webpackImporter?, nvue? }
09:18:06.338 at validate (D:\Jm-code\uniapp\cowman\u-cowman\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\node_modules\schema-utils\dist\validate.js:96:11)
09:18:06.359 at Object.loader (D:\Jm-code\uniapp\cowman\u-cowman\node_modules\@dcloudio\vue-cli-plugin-uni\packages\sass-loader\dist\index.js:38:28)

**系统信息:**
 - 发行平台: [App等]
 - 操作系统 [Android 6.1]
 - HBuilderX版本 [3.3.11]
 - uni-app版本 [uni-app v3.3.11   uni-app cli v2.0.1-33920220208001]
 - 设备信息 
 - Environment Info:

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
  Binaries:
    Node: 14.16.0 - D:\sofeware\Nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.3 - D:\sofeware\Nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmPackages:
    @dcloudio/types: * => 2.5.17
    @dcloudio/uni-app-plus: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-cli-i18n: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-cli-shared: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-h5: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-migration: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-360: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-alipay: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-baidu: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-jd: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-kuaishou: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-lark: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-qq: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-toutiao: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-vue: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-mp-weixin: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-quickapp-native: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-quickapp-webview: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-stat: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/uni-template-compiler: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-33920220208001 => 2.0.1-33920220208001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.15
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.15
    @vue/cli-plugin-babel: ~4.5.15 => 4.5.15
    @vue/cli-plugin-eslint: ~4.5.15 => 4.5.15
    @vue/cli-plugin-router:  4.5.15
    @vue/cli-plugin-vuex:  4.5.15
    @vue/cli-service: ~4.5.15 => 4.5.15
    @vue/cli-shared-utils:  4.5.15
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.2.31
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-eslint-parser:  7.11.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-router:  3.0.1
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
    "node-sass": "^4.14.1",
    "sass-loader": "^7.1.0",

**Comment by AK47-dadada** [comment]
来人呐~~~~

**Comment by AK47-dadada** [comment]
问题已处理，在社区找到了解决方案：

#yarn
yarn add sass-loader@^8
#npm
npm install yarn sass-loader@^8

https://ask.dcloud.net.cn/question/139291
