### ISSUE TITLE
vite 运行命令如何加参数？

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3318]
**问题描述**
例如想传递给vite `base`或者`mode`参数

```shell
npm run build:h5 --base /xxx/
npm run build:h5 --mode test
```

经实验是无法生效的

**预期结果**
打包时读取运行命令参数

**实际结果**
不生效

**系统信息:**
 - uni-app@^3.0.0-alpha-3030820220114003

**Comment by fxy060608** [comment]
`npm run build:h5 -- --mode test`

**Comment by okxiaoliang4** [comment]
不支持`base`参数吗

```shell
npm run build:h5 -- --base /xxx/

CACError: Unknown option `--base`
    at Command.checkUnknownOptions (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:404:17)
    at CAC.runMatchedCommand (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:602:13)
    at CAC.parse (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/Users/apple/work/project/params-examination/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-3030820220114003_e7e4ad921c3cce0160529b62c1b7b435/node_modules/@dcloudio/vite-plugin-uni/dist/cli/index.js:50:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:14)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
```

**Comment by fxy060608** [comment]
> 不支持`base`参数吗。或许我可以用`cross-env`去解决好点。谢谢
> 
> ```shell
> npm run build:h5 -- --base /xxx/
> 
> CACError: Unknown option `--base`
>     at Command.checkUnknownOptions (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:404:17)
>     at CAC.runMatchedCommand (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:602:13)
>     at CAC.parse (/Users/apple/work/project/params-examination/node_modules/.pnpm/cac@6.7.12/node_modules/cac/dist/index.js:541:12)
>     at Object.<anonymous> (/Users/apple/work/project/params-examination/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-3030820220114003_e7e4ad921c3cce0160529b62c1b7b435/node_modules/@dcloudio/vite-plugin-uni/dist/cli/index.js:50:5)
>     at Module._compile (internal/modules/cjs/loader.js:1085:14)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
>     at Module.load (internal/modules/cjs/loader.js:950:32)
>     at Function.Module._load (internal/modules/cjs/loader.js:790:14)
>     at Module.require (internal/modules/cjs/loader.js:974:19)
>     at require (internal/modules/cjs/helpers.js:92:18)
> ```

目前支持的参数列表：
https://github.com/dcloudio/uni-app/blob/next/packages/vite-plugin-uni/src/cli/index.ts
