### ISSUE TITLE
[renderjs] this.$ownerInstance.callMethod 在app真机调试下异常

### ISSUE THREAD

**Issue by parselife** [dcloudio/uni-app#3324]
**问题描述**

使用`renderjs` 来实现外部库的加载后，在h5环境下测试没问题，但是在app真机测试下，出现几个问题：
1. 在组件中使用类似 `@click="module.method"` 报错
```
TypeError: Cannot read property '__ownerId' of undefined
00:18:27.500 at sl (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:3:117381)
00:18:27.522 at nx (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:3:117312)
00:18:27.543 at i (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:3:121509)
00:18:27.569 at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:3:38440
00:18:27.590 at Yt (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:2:22221)
00:18:27.614 at ft (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:2:22298)
00:18:27.635 at ft (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:2:22392)
00:18:27.657 at HTMLElement.r (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/
```
3. 在renderjs module中使用 this.$ownerInstance.callMethod  没有效果（不报错）

**代码片段**

```html
<template>
	<view class="map-container">
		<!-- #ifdef APP-PLUS || H5 -->
		<view id="map-view">
			<!-- 这里是地图容器 -->
			<view class="coords-area" v-if="lnglat!==undefined">
				{{`${lnglat[0]},${lnglat[1]}`}}
			</view>
		</view>
		<button type="primary" @click="mapview.getCoords">
			获取经纬度
		</button>
		<!-- #endif -->
	</view>
</template>

<script setup lang="ts">
	import {
		ref
	} from 'vue'

	const lnglat = ref < (number | string)[] > ()
	defineExpose({
		lnglat,
             showCoords
	})
	function showCoords(data: any) {
		console.log(`接收到来自renderjs的数据: ${JSON.stringify(data)}`)
		lnglat.value = data.lngLat
	}
</script>
<script module="mapview" lang="renderjs">
	let map
	export default {
		mounted() {
			console.log('renderjs mounted...')
			// 动态引入较大类库避免影响页面展示
			const script = document.createElement('script')
			// view 层的页面运行在 www 根目录，其相对路径相对于 www 计算
			script.src = 'static/lib/maplibre-gl.js'
			script.onload = this.createdMap.bind(this)
			document.head.appendChild(script)
		},
		methods: {
			createdMap() {
				//创建地图		
				map = new maplibregl.Map({
					container: 'map-view',
					style: 'https://demotiles.maplibre.org/style.json',
					center: [109, 31.69],
					zoom: 3,
					hash: true
				})
				map.on("load", () => {
					console.log('map load')
					map.on('click', (e) => {
						console.log(e.lngLat)
						// 调用vue组件的方法 这里失败 但没有报错信息
						this.$ownerInstance.callMethod('showCoords', {
							lngLat: [e.lngLat.lng.toFixed(3), e.lngLat.lat.toFixed(3)]
						})
					})
				});
			},
                    // 这个方法不会被触发
			getCoords(event, ownerInstance) {
				console.log('to enable map click')
			}
		}
	}
</script>
```

**预期结果**
app端和h5端表现一致

**实际结果**
app端报错 h5端正常

**系统信息:**
 - 发行平台: H5+ App  vue3
 - HBuilderX版本  3.3.11.20220209
 - vue版本： vue3

**Comment by parselife** [comment]
打印了 `console.log(this.$ownerInstance.callMethod)` 发现可以输出函数定义，我现在怀疑是不是这个方法还不支持 vue3？

**Comment by zhetengbiji** [comment]
HBuilderX

**Comment by LittleSource** [comment]
HBuilderX 3.6.18.20230117 实测 在vue3使用this.$ownerInstance.callMethod 没有反应，建议重新开启这个 issues

**Comment by HKH01** [comment]
不要用<script setup>语法糖，而是换成export default defineComponent({ })
