### ISSUE TITLE
cli命令行创建项目失败

### ISSUE THREAD

**Issue by tangyujing-327** [dcloudio/uni-app#3405]
**问题描述**
执行vue create -p dcloudio/uni-preset-vue my-project失败

**复现步骤**
[复现问题的步骤]
1.  执行npm install -g @vue/cli@4
2. 执行vue create -p dcloudio/uni-preset-vue my-project
3. 报错： ERROR  Failed fetching remote preset dcloudio/uni-preset-vue:
 ERROR  RequestError: unable to verify the first certificate
RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/_got@8.3.2@got/index.js:182:22)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
 ERROR  Failed fetching remote preset dcloudio/uni-preset-vue:
 ERROR  RequestError: unable to verify the first certificate
RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/@vue/cli/node_modules/_got@8.3.2@got/index.js:182:22)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:400:28)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)

**系统信息:**

**补充信息**
mac

**Comment by fxy060608** [comment]
https://www.cnblogs.com/nwy2012/p/15747853.html
