### ISSUE TITLE
CLI创建的Vue3/Vite版UNIAPP项目在MAC M1平台上无法运行

### ISSUE THREAD

**Issue by lvzhenbo** [dcloudio/uni-app#3466]
**问题描述**
无法运行，分析下来大概是vite-plugin-uni->esbulid->vite的问题，调用的是esbuild-darwin-64，但M1用的是esbuild-darwin-arm64
具体log
```
failed to load config from /Users/sli/Desktop/test/my-vue3-project/vite.config.js
09:33:46.677 error when starting dev server:
09:33:46.682 Error: 
09:33:46.683 You installed esbuild on another platform than the one you're currently using.
09:33:46.685 This won't work because esbuild is written with native code and needs to
09:33:46.685 install a platform-specific binary executable.
09:33:46.687 Specifically the "esbuild-darwin-arm64" package is present but this platform
09:33:46.688 needs the "esbuild-darwin-64" package instead. People often get into this
09:33:46.689 situation by installing esbuild on Windows or macOS and copying "node_modules"
09:33:46.689 into a Docker image that runs Linux, or by copying "node_modules" between
09:33:46.691 Windows and WSL environments.
09:33:46.691 If you are installing with npm, you can try not copying the "node_modules"
09:33:46.693 directory when you copy the files over, and running "npm ci" or "npm install"
09:33:46.695 on the destination platform after the copy. Or you could consider using yarn
09:33:46.695 instead which has built-in support for installing a package on multiple
09:33:46.697 platforms simultaneously.
09:33:46.698 If you are installing with yarn, you can try listing both this platform and the
09:33:46.698 other platform in your ".yarnrc.yml" file using the "supportedArchitectures"
09:33:46.700 feature: https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures

09:33:46.700 Keep in mind that this means multiple copies of esbuild will be present.
09:33:46.702 Another alternative is to use the "esbuild-wasm" package instead, which works
09:33:46.702 the same way on all platforms. But it comes with a heavy performance cost and
09:33:46.711 can sometimes be 10x slower than the "esbuild" package, so you may also not
09:33:46.712 want to do that.
09:33:46.715     at generateBinPath (/Users/sli/Desktop/test/my-vue3-project/node_modules/esbuild/lib/main.js:1788:17)
09:33:46.716     at esbuildCommandAndArgs (/Users/sli/Desktop/test/my-vue3-project/node_modules/esbuild/lib/main.js:1872:31)
09:33:46.718     at ensureServiceIsRunning (/Users/sli/Desktop/test/my-vue3-project/node_modules/esbuild/lib/main.js:2034:25)
09:33:46.718     at Object.build (/Users/sli/Desktop/test/my-vue3-project/node_modules/esbuild/lib/main.js:1927:26)
09:33:46.720     at bundleConfigFile (/Users/sli/Desktop/test/my-vue3-project/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:61627:34)
09:33:46.722     at loadConfigFromFile (/Users/sli/Desktop/test/my-vue3-project/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:61604:35)
09:33:46.722     at resolveConfig (/Users/sli/Desktop/test/my-vue3-project/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:61134:34)
09:33:46.725     at createServer (/Users/sli/Desktop/test/my-vue3-project/node_modules/vite/dist/node/chunks/dep-27bc1ab8.js:58974:26)
09:33:46.725     at createServer (/Users/sli/Desktop/test/my-vue3-project/node_modules/@dcloudio/vite-plugin-uni/dist/cli/server.js:15:50)
09:33:46.727     at CAC.runDev (/Users/sli/Desktop/test/my-vue3-project/node_modules/@dcloudio/vite-plugin-uni/dist/cli/action.js:21:45)
```

**复现步骤**

在MAC M1平台使用命令`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`创建项目并安装依赖，然后运行项目

[或者可以直接贴源代码]

**预期结果**
项目能够正常运行

**实际结果**
项目无法正常运行

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Mac OS 12.0.1
 - HBuilderX版本 3.4.7.20220422
 - uni-app版本 3.0.0-alpha-3040720220422002

**Comment by gemone** [comment]
该问题应该溯源到 `vite`。

**Comment by lvzhenbo** [comment]
> 该问题应该溯源到 `vite`。

这或许并不是vite的问题，因为我在vite那里并没有看到相关的反馈，并且我的另一个vite+vue3的后台项目是可以在mac m1上运行的

**Comment by fxy060608** [comment]
已确认为 HBuilderX 的问题，后续会修复

**Comment by gswy** [comment]
遇到了相同的问题。现在有替代方案吗？
不管用不用HBuilderX，能进行真机或者模拟器调试APP的方案。

**Comment by gswy** [comment]
@fxy060608 非常感谢，可以了

**Comment by hentailong** [comment]
这个问题还没解决吗。。。。。

**Comment by lizhil** [comment]
M1还没解决

**Comment by zhetengbiji** [comment]
> M1还没解决

你是 CLI 创建的工程吗？

**Comment by Otto-J** [comment]
是 vue3+vite 的项目吗？如果是的话，这个 https://gitcode.net/xiurensha5731/uni-app-questions 可直接运行的 demo 你可以运行吗，
如果不是这个方案，请开新贴进行沟通

**Comment by Otto-J** [comment]
> M1还没解决

是 vue3+vite 的项目吗？如果是的话，这个 https://gitcode.net/xiurensha5731/uni-app-questions 可直接运行的 demo 你可以运行吗，
如果不是这个方案，请开新贴进行沟通
