### ISSUE TITLE
HBuilder X 3.5.0 -alpha 重新运行编译会报错

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3650]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
![image](https://user-images.githubusercontent.com/60598432/175472154-1cff0afb-ab6d-44d6-9234-5a5d7846f684.png)
下面报错文件夹`uview`是使用easycome了自动导入的文件夹。
项目是Vue3版
运行到微信小程序，然后停止运行，然后再次运行就会报错，而且有时候再次运行两次还是报错，到第三次才会成功编译
本地node版本 v16.14.2 ，目测是node的`rmdirSync`报错了？
报错代码如下
```
error during build:
13:54:22.163 Error: ENOTEMPTY: directory not empty, rmdir 'D:\项目\unpackage\dist\dev\mp-weixin\components\uview'
13:54:22.164     at Object.rmdirSync (fs.js:850:3)
13:54:22.177     at emptyDir (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-cli-shared\dist\fs.js:18:26)
13:54:22.178     at emptyDir (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-cli-shared\dist\fs.js:17:13)
13:54:22.189     at buildOptions (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-mp-vite\dist\plugin\build.js:19:39)
13:54:22.194     at Object.config (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-mp-vite\dist\plugin\index.js:51:49)
13:54:22.200     at resolveConfig (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:61456:33)
13:54:22.204     at processTicksAndRejections (internal/process/task_queues.js:97:5)
13:54:22.209     at async doBuild (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41539:20)
13:54:22.212     at async build (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\vite\dist\node\chunks\dep-8f5c9290.js:41527:16)
13:54:22.220     at async CAC.runDev (D:\软件\HBuilderX.3.4.17.20220614-alpha\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\vite-plugin-uni\dist\cli\action.js:28:30)
```

**预期结果**
重新运行不报错

**实际结果**
报错

**系统信息:**
win 10 
node版本 v16.14.2

**Comment by fxy060608** [comment]
可以将`HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-cli-shared/dist/fs.js` 中的内容，替换为以下，然后再试试看
```js
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.emptyDir = void 0;
const fs_extra_1 = require("fs-extra");
function emptyDir(dir) {
    return (0, fs_extra_1.emptyDirSync)(dir);
}
exports.emptyDir = emptyDir;

```

**Comment by Michael-py001** [comment]
经测试，换成`fs-extra`库已经运行正常
