### ISSUE TITLE
CACError: Unknown option `--minify`

### ISSUE THREAD

**Issue by Cowjiang** [dcloudio/uni-app#3744]
编译至微信小程序时，试图启用Dev的minify压缩，报错

```
> uni -p mp-weixin --minify
```
 
throw new CACError(`Unknown option \`${name.length > 1 ? `--${name}` : `-${name}`}\``);
          ^

CACError: Unknown option `--minify`
    at Command.checkUnknownOptions (E:\school-assistant-client\node_modules\cac\dist\index.js:404:17)
    at CAC.runMatchedCommand (E:\school-assistant-client\node_modules\cac\dist\index.js:602:13)
    at CAC.parse (E:\school-assistant-client\node_modules\cac\dist\index.js:541:12)
    at Object.<anonymous> (E:\school-assistant-client\node_modules\@dcloudio\vite-plugin-uni\dist\cli\index.js:51:5)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)

Process finished with exit code 1

环境：vite vue3.2 ts

**Comment by chouchouji** [comment]
最新版无此问题，可升级到最新版
