### ISSUE TITLE
pinia在app端白屏报错

### ISSUE THREAD

**Issue by mlsjla** [dcloudio/uni-app#3853]
**问题描述**
## app端白屏报错，vue页面，vue3  typescript  小程序和H5页面正常
```
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->
 at useStore (app-service.js:2230:15)
 at  (app-service.js:2839:21)
 at  (app-service.js:11708:3)

```

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**

**实际结果**

## app端白屏报错，vue页面，vue3  typescript  小程序和H5页面正常
```
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->
 at useStore (app-service.js:2230:15)
 at  (app-service.js:2839:21)
 at  (app-service.js:11708:3)

```

**系统信息:**

**补充信息**

**Comment by StrivingRabbit** [comment]
提供示例代码

**Comment by mlsjla** [comment]
@StrivingRabbit 

已经处理过了， 原因是store如果在外部js引入，  可能没初始化的情况下， 会白屏。

将useXXXStore()放在setup后执行， 就行可以了

**Comment by bluelakex** [comment]
在.vue文件中放在setup之后执行是没问题，但是放在.ts文件中执行还是报同样的问题。。。。

**Comment by bluelakex** [comment]
在.vue文件中放在setup之后执行是没问题，但是放在.ts文件中执行还是报同样的问题。。。。

**Comment by dalugm** [comment]
同样遇到这个问题，最小示例代码如下

[my-vue3-project.zip](https://github.com/dcloudio/uni-app/files/10789937/my-vue3-project.zip)

---

uniapp 版本 3.0.0-alpha-3070220230217001，hbuilderx 版本 3.7.2 alpha

根本不需要引用 `useXXXStore()`，只要在 main.ts 里用了 pinia，项目在 app 端就跑不起来

**Comment by link-zh** [comment]
1. main.ts 中要 `return { Pinia }`
2. vue 文件中使用, `usexxxStore()` 要在 setup 之后调用
3. ts 文件中使用, `usexxxStore()` 放在函数内部调用，不要在 ts 文件顶部 import 之后就调用，这样会报错
