### ISSUE TITLE
build:h5打包失败

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-app#388]
**问题描述**
根据文档快速开始，选择hello-uni工程，其他模式都没有问题，build:h5打包出错

**复现步骤**
根据官方文档上面的快速开始，使用cli创建工程，模板选择 hello uni

![image](https://user-images.githubusercontent.com/5308436/57738152-e3510380-76e0-11e9-8b7e-d6ff25b0457a.png)

**预期结果**
希望build:h5没有错误，正确生成打包文件

**实际结果**

```
 ERROR  Failed to compile with 127 errors                                                             上午7:07:00

 error  in ./src/App.vue?vue&type=style&index=0&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: decl.moveTo is not a function
    at /Users/bruce/Documents/my/tn/my-project/src/App.vue:565:1
    at /Users/bruce/Documents/my/tn/my-project/src/App.vue:566:2
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:246:22
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:242:18
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:239:18
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:237:19)
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:267:13
    at LazyResult.run (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)

 @ ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/h5-vue-style-loader??ref--6-oneOf-1-0!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--6-oneOf-1-1!./node_modules/css-loader??ref--6-oneOf-1-2!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-oneOf-1-3!./node_modules/postcss-loader/src??ref--6-oneOf-1-4!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader!./node_modules/wrap-loader??ref--17!./src/App.vue?vue&type=style&index=0&lang=css& 4:14-654
 @ ./src/App.vue?vue&type=style&index=0&lang=css&
 @ ./src/App.vue
 @ ./src/main.js
 @ multi ./src/main.js

 error  in ./src/pages/template/uparse-html/uparse-html.vue?vue&type=style&index=0&id=77cc7aa0&scoped=true&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: decl.moveTo is not a function
    at /Users/bruce/Documents/my/tn/my-project/src/pages/template/uparse-html/uparse-html.vue:180:1
    at /Users/bruce/Documents/my/tn/my-project/src/pages/template/uparse-html/uparse-html.vue:181:3
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:246:22
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Rule.each (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Rule.walk (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:242:18
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:239:18
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:135:18
    at Root.each (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:101:16)
    at Root.walk (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:131:17)
    at Root.walkRules (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/container.js:237:19)
    at /Users/bruce/Documents/my/tn/my-project/node_modules/postcss-merge-rules/dist/index.js:267:13
    at LazyResult.run (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:295:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:208:26)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
    at LazyResult.asyncTick (/Users/bruce/Documents/my/tn/my-project/node_modules/postcss-loader/node_modules/postcss/lib/lazy-result.js:221:14)
```

**系统信息:**
 - 发行平台:H5平台
 - uni-app版本 `npm run info`

```
npm run info

> my-project@0.1.0 info /Users/bruce/Documents/my/tn/my-project
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js


Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 11.0.0 - /usr/local/bin/node
    Yarn: 1.9.4 - ~/.yarn/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.131
    Firefox: 63.0.3
    Safari: 12.1
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.232
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.949
    @dcloudio/uni-h5: * => 0.5.1
    @dcloudio/uni-mp-alipay: * => 0.0.803
    @dcloudio/uni-mp-baidu: * => 0.0.830
    @dcloudio/uni-mp-toutiao: * => 0.0.328
    @dcloudio/uni-mp-weixin: * => 0.0.952
    @dcloudio/uni-template-compiler: * => 0.9.169
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.509
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.462
    @dcloudio/webpack-uni-mp-loader: * => 0.3.619
    @dcloudio/webpack-uni-pages-loader: * => 0.2.827
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0
  npmGlobalPackages:
    @vue/cli: 3.1.3

```

 - 设备信息 
模拟器

**补充信息**
前一段时间试是可以的

**Comment by niquo88** [comment]
我也遇到这个问题，使用的最新的1.9.7.20190516-alpha版本，uni-app H5无法打包，错误同上，希望能解决。

**Comment by fxy060608** [comment]
vue cli 版本太低，建议升级为最新

**Comment by brucehelen** [comment]
> vue cli 版本太低，建议升级为最新

试了下载最新版本的 `vue cli`，还是报错

```bash
$ vue -V
3.7.0
```

![image](https://user-images.githubusercontent.com/5308436/57861167-b445a980-7828-11e9-9f62-43b04adef4b9.png)

**Comment by fxy060608** [comment]
> > vue cli 版本太低，建议升级为最新
> 
> 试了下载最新版本的 `vue cli`，还是报错
> 
> ```shell
> $ vue -V
> 3.7.0
> ```
> 
> ![image](https://user-images.githubusercontent.com/5308436/57861167-b445a980-7828-11e9-9f62-43b04adef4b9.png)

清空 node_modules 和 package-lock.json 文件，重新 npm install 试下，这个问题应该是依赖库的版本导致的

**Comment by zencodex** [comment]
安装最新的这两个包，否则里面调用的是旧版本的 postcss-loader

`npm install postcss-merge-rules cssnano`

**Comment by brucehelen** [comment]
> 安装最新的这两个包，否则里面调用的是旧版本的 postcss-loader
> 
> `npm install postcss-merge-rules cssnano`

安装了这两个包，可以了，谢谢！

**Comment by brucehelen** [comment]
全新安装了包，又出新的问题：

```javascript
<template>
  <div class="content">
    <div class="title">{{title}}</div>
    <div class="detail">{{detail}}</div>
  </div>
</template>

<script>
export default {
  props: {
    title: String,
    detail: String
  }
}
</script>

<style lang="less" scoped>
.content {
  margin-top: 35upx;
  .title {
    font-size:36upx;
    font-weight:bold;
    color:rgba(51,51,51,1);
    text-align: center;
  }
  .detail {
    margin-top: 20upx;
    text-align: center;
    font-size:24upx;
    font-weight:bold;
    color:rgba(153,153,153,1);
  }
}
</style>

```

![image](https://user-images.githubusercontent.com/5308436/57997415-13dcd700-7aff-11e9-9c86-3bc4e8699d6c.png)

**Comment by brucehelen** [comment]
#395
