### ISSUE TITLE
uni.previewImage在h5端报错

### ISSUE THREAD

**Issue by gyhyfj** [dcloudio/uni-app#3974]
预览大图功能正常，但当关闭大图时候不是点击左上角X按钮，而是点击遮罩层，就会在控制台报错：

```js
Uncaught TypeError: Cannot read properties of null (reading 'style')
    at _setTransform (uni-h5.es.js:9912:19)
    at uni-h5.es.js:10275:11
    at fn (uni-h5.es.js:9711:7)
```
版本：`3.0.0-alpha-3060420220922001`

**Comment by StrivingRabbit** [comment]
升级下包依赖版本
