### ISSUE TITLE
App端，renderjs+html2canvas 基于uni.canvasToTempFilePath生成路径失败

### ISSUE THREAD

**Issue by summer-07** [dcloudio/uni-app#4196]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
App端，renderjs+html2canvas 基于 uni.canvasToTempFilePath 无法生成临时图片路径

示例代码：
// 这是在renderjs中使用的  
export const draw = async (instance: any, referenceId = '#reference', outputId = '#output') => {  
  // 等待字体加载完成  
  await document.fonts.load('12px share-title')  
  await document.fonts.load('12px share-sub-title')  
  await document.fonts.load('12px iconfont')  

  // 获取对比容器  
  const reference = document.querySelector(referenceId)  
  // 开始绘制  
  // @ts-ignore  
  html2canvas(reference, { allowTaint: true, useCORS: true, logging: true }).then((canvas: HTMLCanvasElement) => {  
    const output = document.querySelector(outputId) as HTMLDivElement  
    const outputCanvas = output.querySelector('canvas') as HTMLCanvasElement  

    const ctx = outputCanvas.getContext('2d', { willReadFrequently: true })!  
    const pixelRatio = window.devicePixelRatio  
    const width = canvas.width / pixelRatio  
    const height = canvas.height / pixelRatio  

    // 设置画布宽高  
    output.style.width = width / pixelRatio + 'px'  
    output.style.height = height / pixelRatio + 'px'  
    outputCanvas.height = height  
    outputCanvas.width = width  

    ctx.clearRect(0, 0, width, height)  

    // 将绘制完成的 canvas 放入 uniapp 组件的 canvas  
    ctx.drawImage(canvas, 0, 0, Math.ceil(width / pixelRatio), Math.ceil(height / pixelRatio))  

    instance.$ownerInstance.callMethod('changeLoading')  
  })  
}
操作步骤：
1.DOM 模板

```<div>  
    <div  
           id="reference"  
           class="absolute top-0 left-0 w-full bg-cover bg-no-repeat h-[100vh]"  
         >  
          <image src="/static/images/default.png" alt="" />  
    </div>  

    <canvas id="output" canvas-id="output-canvas"></canvas>  
</div>```
2.使用 renderjs 模块

```<script module="render" lang="renderjs">  
import { draw } from '@/utils/share'  

export default {  
  methods: {  
    async updateData(modelValue) {  
      if (modelValue) { draw(this) }  
    }  
  },  
}  
</script>```
3.基于渲染的 dom 元素 渲染成为 canvas
```
// 这是在renderjs中使用的  
export const draw = async (instance: any, referenceId = '#reference', outputId = '#output') => {  
  // 等待字体加载完成  
  await document.fonts.load('12px share-title')  
  await document.fonts.load('12px share-sub-title')  
  await document.fonts.load('12px iconfont')  

  // 获取对比容器  
  const reference = document.querySelector(referenceId)  
  // 开始绘制  
  // @ts-ignore  
  html2canvas(reference, { allowTaint: true, useCORS: true, logging: true }).then((canvas: HTMLCanvasElement) => {  
    const output = document.querySelector(outputId) as HTMLDivElement  
    const outputCanvas = output.querySelector('canvas') as HTMLCanvasElement  

    const ctx = outputCanvas.getContext('2d', { willReadFrequently: true })!  
    const pixelRatio = window.devicePixelRatio  
    const width = canvas.width / pixelRatio  
    const height = canvas.height / pixelRatio  

    // 设置画布宽高  
    output.style.width = width / pixelRatio + 'px'  
    output.style.height = height / pixelRatio + 'px'  
    outputCanvas.height = height  
    outputCanvas.width = width  

    ctx.clearRect(0, 0, width, height)  

    // 将绘制完成的 canvas 放入 uniapp 组件的 canvas  
    ctx.drawImage(canvas, 0, 0, Math.ceil(width / pixelRatio), Math.ceil(height / pixelRatio))  

    instance.$ownerInstance.callMethod('changeLoading')  
  })  
}```
预期结果：
预期结果是可以下载canvas的文件

实际结果：
```
23:31:24.457 [TIP] :#1 0ms Starting document clone with size 394x804 scrolled to 0,0 at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.181 [TIP] :#1 722ms Document cloned, element located at -394.18182373046875,0 with size 394.18182373046875x700 using computed rendering at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.190 [TIP] :#1 722ms Starting DOM parsing at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.245 [TIP] :#1 782ms Added image file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/static/images/default.png at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.261 [TIP] :#1 799ms Starting renderer for element at -394.18182373046875,0 with size 395x700 at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.263 [TIP] :#1 800ms Canvas renderer initialized (395x700) with scale 2.75 at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.308 [TIP] :#1 850ms Finished rendering at https://img.coregem.net/js/html2canvas.min.js:22  
23:31:25.324 Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.  
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.  
    at o (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:155807)  
    at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29262)  
    at Ca (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29339)  
    at qa (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:31263)  
    at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:151322  
    at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29262)  
    at Ca (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29339)  
    at _ (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:34185)  
    at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29270)  
    at Ua (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:30772) at uni-app-view.umd.js:1
bug描述：
使用 renderjs + html2canvas 在App端引入本地图片渲染报错
Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The canvas has been tainted by cross-origin data.
at o (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:155807)
at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29262)
at Ca (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29339)
at qa (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:31263)
at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:151322
at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29262)
at Ca (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29339)
at _ (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:34185)
at Ea (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:29270)
at Ua (file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/uni-app-view.umd.js:1:30772) at uni-app-view.umd.js:1
```
 
产品分类： uniapp/App

- PC开发环境操作系统： WindowsPC
- 开发环境操作系统版本号： 11
- HBuilderX类型： 正式HBuilderX
- 版本号： 3.7.6
- 手机系统： Android
- 手机系统版本号： Android 10
- 手机厂商： 小米
- 手机机型： Redmi Note 9
- 页面类型： vue
- vue版本： vue3
- nvue编译模式： fast
- 打包方式： 云端
- 项目创建方式： HBuilderX

![微信图片_20230312233529](https://user-images.githubusercontent.com/58579560/224557275-7cbbd3a9-ab41-4e37-94cf-125bb55431bd.png)
![微信图片_20230312233657](https://user-images.githubusercontent.com/58579560/224557278-8028f647-31ce-4679-a837-3764b96329a3.png)

**Comment by zhetengbiji** [comment]
即使本地图像也可能存在跨域问题，给你一些参考：https://github.com/dcloudio/uni-app/blob/e7902890bbf888c5dfe91d9b6cea23e8c83cf69d/src/core/view/components/canvas/index.vue#L326，看是否有帮助。

**Comment by GRCmade** [comment]
长时间未回复，关闭 issue，如果还存在这个问题，可以重新打开
