### ISSUE TITLE
uniad web上使用报错

### ISSUE THREAD

**Issue by chenhaihong** [dcloudio/uni-app#4344]
**问题描述**
h5上使用uniad报错。

**复现步骤**

使用如下代码，
控制台报错。
``` 
<!-- H5-三图信息流 -->
<ad adpid="1900960140"></ad>
<!-- H5-大图信息流 -->
<ad adpid="1181332226"></ad>
```

[或者可以直接贴源代码]

**预期结果**
不报错，或者提示错误原因。

**实际结果**
报错，错误如下，

```
[system] TypeError: Cannot read properties of undefined (reading '1900960140')
    at t.value (chunk-vendors.fdb31ef8.js:1:45728)
    at chunk-vendors.fdb31ef8.js:1:46123
    at Array.forEach (<anonymous>)
    at Function.success (chunk-vendors.fdb31ef8.js:1:46065)
    at chunk-vendors.fdb31ef8.js:1:111993
    at Object.j [as callback] (chunk-vendors.fdb31ef8.js:1:114383)
    at y (chunk-vendors.fdb31ef8.js:1:115087)
    at S.onload (chunk-vendors.fdb31ef8.js:1:72849)
```

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [3.7.11]

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
这段代码没错空判断，导致报错，
https://github.com/dcloudio/uni-app/blob/c860345d22b9ae6387620e2f9b4cabc85a267908/src/platforms/h5/view/components/ad/index.vue#L82

```javascript
  _doCallback (adpid, success, fail) {
    AdConfig.IS++
    var { a, b } = this._adConfig
    if (a[adpid]) { // 这行代码没有判断a为空的情况，导致报错。需要修改为 a && a[adpid]
      success(b, a[adpid])
    } else {
      fail(this.ERROR_INVALID_ADPID)
    }
  }
```

**Comment by GRCmade** [comment]
hello , 你使用新版本的时候，是否还存在这个问题？
