### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'shown')

### ISSUE THREAD

**Issue by baiyajin** [dcloudio/uni-app#4383]
**问题描述**

使用 npx degit dcloudio/uni-preset-vue#vite my-vue3-project 创建的 Vue3/Vite版
在项目中使用 vk-uview-ui 框架下的 u-tabbar 组件
    <u-tabbar v-model="current" :list="list" :mid-button="true"></u-tabbar>
报错如下错误

uni-h5.es.js:21786  Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'shown')
    at setTabBar (uni-h5.es.js:21786:21)
    at uni-h5.es.js:21845:5
    at uni-h5.es.js:3112:12
    at invokeApi (uni-h5.es.js:2975:10)
    at uni-h5.es.js:2997:11
    at new Promise (<anonymous>)
    at Module.hideTabBar (uni-h5.es.js:2996:9)
    at Proxy.created (u-tabbar.vue:78:1)
    at callWithErrorHandling (vue.runtime.esm.js:1375:36)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1384:21)

**复现步骤**
[复现问题的步骤]
1.  启动 Vue3/Vite版的uniapp
2. 引入 vk-uview-ui 框架下的 u-tabbar 组件
3. 启动控制台报错

[或者可以直接贴源代码]

**预期结果**
不要提示 undefined  不能设置 shown
**实际结果**
![image](https://github.com/dcloudio/uni-app/assets/49177898/01d8df7e-2647-472e-9827-a81968ad506c)

**系统信息:**
 - 发行平台:  H5平台
 - 操作系统 windows11
 - HBuilderX版本 3.8.4

**补充信息**
[可选]
问题出在你们这个文件 uni-h5.es.js

**Comment by fulus06** [comment]
一样的问题

**Comment by lewei-space** [comment]
"tabBar": {}  为空会报这个错误，配置好 然后隐藏原生tabBar uni.hideTabBar() 控制台就不出现红色警戒了

**Comment by GRCmade** [comment]
你好，三方插件，请到三方插件社区回复
