### ISSUE TITLE
【报BUG】依赖包版本异常 TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by sqTwins** [dcloudio/uni-app#4450]
**问题描述**
同一工程代码, 在不同时间npm install , 会有不同的结果, run serve可能会失败, 
**已查明大致BUG原因**

**复现步骤**
1.  删除package-lock.json
2. npm install
3. npm run serve

**补充信息**
**在不同时间npm install , 会有不同的 package-lock.json, 请官方使用固定版本的依赖包!!!! **
猜测Cli依赖的版本出现异常
为了对比不能编译的lock.json和可以编译的lock.json,  写了个简单脚本, 查询所有依赖包版本差异如下:
[希望->  代表可以编译的lock.json, 但是->   代表不可编译的lock.json]
版本差异-结果: 66       总数对比: 1237 : 1237
希望:@types/eslint=8.44.0  但是: @types/eslint=8.44.1
希望:@types/node=20.4.2  但是: @types/node=20.4.5
希望:@webassemblyjs/ast=1.11.6  但是: @webassemblyjs/ast=1.9.0
希望:@webassemblyjs/floating-point-hex-parser=1.11.6  但是: @webassemblyjs/floating-point-hex-parser=1.9.0
希望:@webassemblyjs/helper-api-error=1.11.6  但是: @webassemblyjs/helper-api-error=1.9.0
希望:@webassemblyjs/helper-buffer=1.11.6  但是: @webassemblyjs/helper-buffer=1.9.0
希望:@webassemblyjs/helper-wasm-bytecode=1.11.6  但是: @webassemblyjs/helper-wasm-bytecode=1.9.0
希望:@webassemblyjs/helper-wasm-section=1.11.6  但是: @webassemblyjs/helper-wasm-section=1.9.0
希望:@webassemblyjs/ieee754=1.11.6  但是: @webassemblyjs/ieee754=1.9.0
希望:@webassemblyjs/leb128=1.11.6  但是: @webassemblyjs/leb128=1.9.0
希望:@webassemblyjs/utf8=1.11.6  但是: @webassemblyjs/utf8=1.9.0
希望:@webassemblyjs/wasm-edit=1.11.6  但是: @webassemblyjs/wasm-edit=1.9.0
希望:@webassemblyjs/wasm-gen=1.11.6  但是: @webassemblyjs/wasm-gen=1.9.0
希望:@webassemblyjs/wasm-opt=1.11.6  但是: @webassemblyjs/wasm-opt=1.9.0
希望:@webassemblyjs/wasm-parser=1.11.6  但是: @webassemblyjs/wasm-parser=1.9.0
希望:acorn=5.7.4  但是: acorn=6.4.2
希望:assert=2.0.0  但是: assert=1.5.0
希望:autoprefixer=8.0.0  但是: autoprefixer=8.6.5
希望:braces=3.0.2  但是: braces=2.3.2
希望:bytes=3.0.0  但是: bytes=3.1.2
希望:camelcase=6.3.0  但是: camelcase=5.3.1
希望:commander=4.1.1  但是: commander=2.20.3
希望:cookie=0.5.0  但是: cookie=0.4.2
希望:cosmiconfig=8.2.0  但是: cosmiconfig=7.1.0
希望:electron-to-chromium=1.4.467  但是: electron-to-chromium=1.4.473
希望:enhanced-resolve=5.15.0  但是: enhanced-resolve=4.5.0
希望:escape-string-regexp=4.0.0  但是: escape-string-regexp=1.0.5
希望:eslint-scope=5.1.1  但是: eslint-scope=4.0.3
希望:fast-glob=3.3.0  但是: fast-glob=3.3.1
希望:fill-range=7.0.1  但是: fill-range=4.0.0
希望:find-up=4.1.0  但是: find-up=3.0.0
希望:icss-utils=5.1.0  但是: icss-utils=4.1.1
希望:is-number=7.0.0  但是: is-number=3.0.0
希望:is-wsl=2.2.0  但是: is-wsl=1.1.0
希望:istanbul-lib-report=3.0.0  但是: istanbul-lib-report=3.0.1
希望:istanbul-reports=3.1.5  但是: istanbul-reports=3.1.6
希望:json5=1.0.2  但是: json5=2.2.3
希望:loader-runner=4.3.0  但是: loader-runner=2.4.0
希望:locate-path=5.0.0  但是: locate-path=3.0.0
希望:lru-cache=4.1.5  但是: lru-cache=5.1.1
希望:make-dir=3.1.0  但是: make-dir=2.1.0
希望:micromatch=4.0.5  但是: micromatch=3.1.10
希望:mini-css-extract-plugin=2.7.6  但是: mini-css-extract-plugin=0.5.0
希望:p-locate=4.1.0  但是: p-locate=3.0.0
希望:path-exists=4.0.0  但是: path-exists=3.0.0
希望:picocolors=0.2.1  但是: picocolors=1.0.0
希望:pkg-dir=4.2.0  但是: pkg-dir=3.0.0
希望:safe-buffer=5.2.1  但是: safe-buffer=5.1.2
希望:sass=1.64.0  但是: sass=1.64.1
希望:semver=5.7.2  但是: semver=6.3.1
希望:serialize-javascript=6.0.1  但是: serialize-javascript=4.0.0
希望:source-map=0.6.1  但是: source-map=0.7.4
希望:ssri=8.0.1  但是: ssri=6.0.2
希望:tapable=2.2.1  但是: tapable=1.1.3
希望:terser=5.19.1  但是: terser=4.8.1
希望:terser-webpack-plugin=5.3.9  但是: terser-webpack-plugin=1.4.5
希望:to-regex-range=5.0.1  但是: to-regex-range=2.1.1
希望:tslib=2.6.0  但是: tslib=2.6.1
希望:vue-loader=17.2.2  但是: vue-loader=15.10.1
希望:watchpack=2.4.0  但是: watchpack=1.7.5
希望:webpack=5.88.2  但是: webpack=4.46.0
希望:which=2.0.2  但是: which=1.3.1
希望:word-wrap=1.2.4  但是: word-wrap=1.2.5
希望:ws=7.5.9  但是: ws=7.4.6
希望:y18n=5.0.8  但是: y18n=4.0.3
希望:yallist=2.1.2  但是: yallist=3.1.1

**预期结果**
运行成功

**实际结果**
几率运行失败
`
TypeError: Cannot convert undefined or null to object
    at Function.assign (<anonymous>)
    at /Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@dcloudio/vue-cli-plugin-uni/lib/chain-webpack.js:53:34
    at Object.tap (/Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/webpack-chain/src/Use.js:14:20)
    at /Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@dcloudio/vue-cli-plugin-uni/lib/chain-webpack.js:53:12
    at Array.forEach (<anonymous>)
    at /Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@dcloudio/vue-cli-plugin-uni/lib/chain-webpack.js:22:17
    at /Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@vue/cli-service/lib/Service.js:268:40
    at Array.forEach (<anonymous>)
    at Service.resolveChainableWebpackConfig (/Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@vue/cli-service/lib/Service.js:268:26)
    at Service.resolveWebpackConfig (/Users/twins/Desktop/3/Demo/emptyJenkinsUniappProject/node_modules/@vue/cli-service/lib/Service.js:272:48)`

**系统信息:**
 - 发行平台: H5
 - 操作系统 MACOS
 - uni-app版本 
 - uni-app v3.8.7
uni-app cli v2.0.2-3080720230703001

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 14.15.0 - ~/.nvm/versions/node/v14.15.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.15.0/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v14.15.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @dcloudio/types: ^3.3.2 => 3.3.3 
    @dcloudio/uni-app: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-app-plus: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-cli-i18n: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-cli-shared: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-h5: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-migration: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-360: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-alipay: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-baidu: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-jd: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-kuaishou: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-lark: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-qq: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-toutiao: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-vue: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-weixin: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-mp-xhs: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-quickapp-native: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-quickapp-webview: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-stacktracey: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-stat: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/uni-template-compiler: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.2-3080720230703001 => 2.0.2-3080720230703001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.4.0 
    @vue/babel-helper-vue-transform-on:  1.1.5 
    @vue/babel-plugin-jsx:  1.1.5 
    @vue/babel-plugin-transform-vue-jsx:  1.4.0 
    @vue/babel-preset-app:  5.0.8 
    @vue/babel-preset-jsx:  1.4.0 
    @vue/babel-sugar-composition-api-inject-h:  1.4.0 
    @vue/babel-sugar-composition-api-render-instance:  1.4.0 
    @vue/babel-sugar-functional-vue:  1.4.0 
    @vue/babel-sugar-inject-h:  1.4.0 
    @vue/babel-sugar-v-model:  1.4.0 
    @vue/babel-sugar-v-on:  1.4.0 
    @vue/cli-overlay:  5.0.8 
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.8 
    @vue/cli-plugin-router:  5.0.8 
    @vue/cli-plugin-vuex:  5.0.8 
    @vue/cli-service: ~5.0.0 => 5.0.8 
    @vue/cli-shared-utils:  5.0.8 
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/composition-api:  1.7.0 
    @vue/devtools-api:  6.0.0-beta.15 
    @vue/shared: ^3.0.0 => 3.3.4 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: >= 2.6.14 < 2.7 => 2.6.14 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.10.1 (17.2.2, 15.10.1)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: >= 2.6.14 < 2.7 => 2.6.14 (2.7.14, 2.6.14)
    vue-template-es2015-compiler:  1.9.1 
    vue3:  1.0.0 
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: 5.0.8

 - 设备信息 chrome

**Comment by xiaoxiaohuayu** [comment]
一年了还没人解决吗？

**Comment by GRCmade** [comment]
长时间未回复，关闭 issue，如果还存在这个问题，可以重新打开
