### ISSUE TITLE
使用plugin-vue-jsx插件后，报错无法启动

### ISSUE THREAD

**Issue by tocurd** [dcloudio/uni-app#4507]
**问题描述**
准备在uniapp中使用tsx进行编程，按照官方文档操作时提示错误

**复现步骤**
[复现问题的步骤]
按照官方文档https://uniapp.dcloud.net.cn/tutorial/syntax-jsx.html操作

```
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import vueJsx from '@vitejs/plugin-vue-jsx'

export default defineConfig({
  plugins: [
    uni(),
    vueJsx({
      // options are passed on to @vue/babel-plugin-jsx
    })
  ],
});
```
```
{
  "devDependencies": {
    "@vitejs/plugin-vue-jsx": "^3.0.2"
  }
}

```

**预期结果**
使用插件@vitejs/plugin-vue-jsx后报错

**实际结果**
```
09:04:13.384 failed to load config from E:\jinye\A.产品\fid\software\ddd\vite.config.js
09:04:13.408 error when starting dev server:
09:04:13.409 E:\jinye\A.产品\fid\software\ddd\node_modules\@vitejs\plugin-vue-jsx\dist\index.cjs:56
09:04:13.414           __VUE_OPTIONS_API__: config.define?.__VUE_OPTIONS_API__ ?? true,
09:04:13.415                                              ^
09:04:13.422 SyntaxError: Unexpected token '.'
09:04:13.427     at wrapSafe (internal/modules/cjs/loader.js:915:16)
09:04:13.427     at Module._compile (internal/modules/cjs/loader.js:963:27)
09:04:13.432     at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
09:04:13.433     at Object.require.extensions.<computed> [as .js] (D:\software\HBuilderX\plugins\uniapp-cli-vite\node_modules\vite\dist\node\chunks\dep-27bc1ab8.js:61682:13)
09:04:13.439     at Module.load (internal/modules/cjs/loader.js:863:32)
09:04:13.440     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
09:04:13.445     at Module.require (internal/modules/cjs/loader.js:887:19)
09:04:13.446     at require (internal/modules/cjs/helpers.js:74:18)
09:04:13.450     at Object.<anonymous> (E:\jinye\A.产品\fid\software\ddd\vite.config.js:30:37)
09:04:13.451     at Module._compile (internal/modules/cjs/loader.js:999:30)
```

**系统信息:**
 - 发行平台: 5+APP
 - 操作系统 Android 7.1
 - HBuilderX版本3.4.6.20220420
 - uni-app版本 
 - 设备信息 RK3288

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by tocurd** [comment]
更新HBuilderX到3.8.12后正常
