### ISSUE TITLE
Vue3 空项目真机调试报错

### ISSUE THREAD

**Issue by devhaozi** [dcloudio/uni-app#4547]
**问题描述**
复现很简单，新建项目选uni-app第一个默认模版，然后真机调试，即可看到报错

**复现步骤**
新建项目选uni-app第一个默认模版，然后连接真机调试，即可看到报错，手机显示为白屏：

```
20:41:46.883 项目 'test' 编译成功。
20:41:46.891 正在同步手机端程序文件...
20:41:47.035 同步手机端程序文件完成
20:41:48.269 App Launch at App.vue:4
20:41:48.270 App Show at App.vue:7
20:41:48.385 [JS Framework] Failed to execute the callback function:
 TypeError: Cannot read property 'meta' of undefined
20:41:48.391 reportJSException >>>> exception function:__WEEX_CALL_JAVASCRIPT__, exception:JavaScript execute error!Uncaught TypeError: Cannot read property 'meta' of undefined
 at KI (uni-jsframework.js:32:240607)
 at JI (uni-jsframework.js:32:240435)
 at emit (uni-jsframework.js:17:11109)
 at subscribeHandler (uni-jsframework.js:32:45543)
 at  (uni-jsframework.js:32:241585)
 at emit (uni-jsframework.js:17:11109)
 at subscribeHandler (uni-jsframework.js:32:45543)
 at Vg (uni-jsframework.js:32:238260)
 at consume (uni-jsframework.js:17:15396)
 at callback (uni-jsframework.js:19:1659)
```

**预期结果**
正常运行

**实际结果**
白屏，且有报错

**系统信息:**
 - 发行平台: 安卓APP
 - 操作系统 安卓13
 - HBuilderX版本 3.8.12.20230817
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 IQOO 11 Pro

**补充信息**
新建vue2项目修复pages.json里面少了一项的问题之后没有报错，真机不支持vue3吗？
![image](https://github.com/dcloudio/uni-app/assets/115467771/64b81fe1-e829-4b8c-9e8e-764e0020483e)

**Comment by yurj26** [comment]
未复现此问题，请提供下测试工程

**Comment by 953133667** [comment]
我也遇到了一模一样的问题，请问有解决方案吗？
