### ISSUE TITLE
vue-cli 无法升级

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#4623]
**问题描述**
vue-cli 无法升级，一直报版本号错误。

**复现步骤**
[复现问题的步骤]
运行 npx @dcloudio/uvm@latest

**预期结果**
正常升级

**实际结果**
node_modules\@dcloudio\uvm\lib\version.js:50
    throw new Error('Invalid version: ' + target)
          ^

Error: Invalid version: 3.98.2023112510
    at find (node_modules\@dcloudio\uvm\lib\version.js:50:11)     
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async start (node_modules\@dcloudio\uvm\bin\index.js:16:19)

**系统信息:**
 - 发行平台: 无关
 - 操作系统: win10
 - HBuilderX版本: 无关
 - uni-app版本: 3.0.0-3070820230323001
 - 设备信息: 无关

**补充信息**
1、官方从 ## 3.8.12.20230817 版本以后，版本号规则变更为 ## 3.94.2023102613、## 3.95.2023102806、## 3.96.2023110403、## 3.98.2023112510，少了一位
2、根据早期代码 @dcloudio\uvm\lib\version.js 的检测规则 const result = target.match(/^(\d+)\.(\d+)\.(\d+)\.(\d+)(-alpha)?$/) 来判断最新代码会报错
3、后续代码会根据版本号解析日期规则，由于少了一位也是会报错

**Comment by hswyxj** [comment]
怎么解决

**Comment by magicwing** [comment]
跳过命令升级方式，删除旧版本，直接更改最新版本号来升级




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年3月9日(星期天) 上午9:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] vue-cli 无法升级 (Issue #4623)



   
怎么解决

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  hswyxj left a comment (dcloudio/uni-app#4623)
 
怎么解决
