### ISSUE TITLE
3.99版本无法调用wx.qy.login

### ISSUE THREAD

**Issue by cos800** [dcloudio/uni-app#4748]
```js
    export default {
        data() {
            return {
                
            }
        },
        onLoad() {
            wx.qy.login({
                complete(res) {
                    console.log('qylogin result:', res);
                }
            });
            
        },
        methods: {
            
        }
    }
```

![image](https://github.com/dcloudio/uni-app/assets/635184/95d4a309-af26-421c-b835-a0da63945588)

**Comment by cos800** [comment]
在 HBuilderX 目录下执行 npx patch-hbuilderx-plugins 失败
```text
$ npx patch-hbuilderx-plugins
Need to install the following packages:
  patch-hbuilderx-plugins@1.0.5
Ok to proceed? (y) y
? HBuilderX Path C:\Program Files\HBuilderX
HBuilderX Version: 3.99.2023122611
C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14258
                        throw new DegitError(`could not find commit hash for ${repo.ref}`, {
                              ^

DegitError: could not find commit hash for v3.99.2023122611
    at Degit._cloneWithTar (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14258:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Degit.clone (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14096:4)
    at async patch (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\patch-hbuilderx-plugins\scripts\patch.js:43:3) {
  code: 'MISSING_REF',
  ref: 'v3.99.2023122611'
}

Node.js v18.17.0
```

**Comment by zhetengbiji** [comment]
> 在 HBuilderX 目录下执行 npx patch-hbuilderx-plugins 失败
> 
> ```
> $ npx patch-hbuilderx-plugins
> Need to install the following packages:
>   patch-hbuilderx-plugins@1.0.5
> Ok to proceed? (y) y
> ? HBuilderX Path C:\Program Files\HBuilderX
> HBuilderX Version: 3.99.2023122611
> C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14258
>                         throw new DegitError(`could not find commit hash for ${repo.ref}`, {
>                               ^
> 
> DegitError: could not find commit hash for v3.99.2023122611
>     at Degit._cloneWithTar (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14258:10)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async Degit.clone (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\degit\dist\index-688c5d50.js:14096:4)
>     at async patch (C:\Users\thisky\AppData\Local\npm-cache\_npx\ab8e574058bea07e\node_modules\patch-hbuilderx-plugins\scripts\patch.js:43:3) {
>   code: 'MISSING_REF',
>   ref: 'v3.99.2023122611'
> }
> 
> Node.js v18.17.0
> ```

确实未发布过针对 3.99 的 patch
