### ISSUE TITLE
vue3 plugin

### ISSUE THREAD

**Issue by 3220005370** [dcloudio/uni-app#4819]
运行微信小程序，编译不通过
HBuilderx版本：4.08

报错如下：
error during build:
22:46:01.931 TypeError: Cannot read properties of undefined (reading 'vueOptions')
22:46:01.956     at Object.<anonymous> (D:\Program Files\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-mp-vite\dist\index.js:27:45)
22:46:01.976     at filterPlugin (file:///D:/Program%20Files/HBuilderX/plugins/uniapp-cli-vite/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:63940:22)
22:46:02.004     at Array.filter (<anonymous>)
22:46:02.036     at resolveConfig (file:///D:/Program%20Files/HBuilderX/plugins/uniapp-cli-vite/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:63951:71)
22:46:02.069     at processTicksAndRejections (node:internal/process/task_queues:96:5)
22:46:02.102     at async Module.build (file:///D:/Program%20Files/HBuilderX/plugins/uniapp-cli-vite/node_modules/vite/dist/node/chunks/dep-934dbc7c.js:46282:20)
22:46:02.142     at async CAC.runDev (D:\Program Files\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\vite-plugin-uni\dist\cli\action.js:56:30)

**Comment by wangjinxin613** [comment]
请提供一下能够复现的最小 demo 工程压缩包

**Comment by yxw007** [comment]
@wangjinxin613 找到问题了，参数传递错了

![b157a9105e2886d478defe2cd4b9a769](https://github.com/user-attachments/assets/46246f10-b489-4041-888e-13a3a7692fb1)
