### ISSUE TITLE
修改代码更新页面的时候会偶发 Cannot read property 'offsetWidth' of null

### ISSUE THREAD

**Issue by 31702160323** [dcloudio/uni-app#4874]
Cannot read property 'offsetWidth' of null
TypeError: Cannot read property 'offsetWidth' of null
    at n (file:///storage/emulated/0/Android/data/uni.UNIB8C97E0/apps/__UNI__B8C97E0/www/uni-app-view.umd.js:1:156303)
    at Fa (file:///storage/emulated/0/Android/data/uni.UNIB8C97E0/apps/__UNI__B8C97E0/www/uni-app-view.umd.js:1:30354)
    at $a (file:///storage/emulated/0/Android/data/uni.UNIB8C97E0/apps/__UNI__B8C97E0/www/uni-app-view.umd.js:1:30431)
    at HTMLDivElement.n (file:///storage/emulated/0/Android/data/uni.UNIB8C97E0/apps/__UNI__B8C97E0/www/uni-app-view.umd.js:1:68283) at uni-app-view.umd.js:1

**Comment by 31702160323** [comment]
![1714279614308](https://github.com/dcloudio/uni-app/assets/46100045/b443ebad-c694-49f1-8089-72a2ea9b5736)
