### ISSUE TITLE
uniapp npm更新到3.0.0-4010420240430001页面控制台报错

### ISSUE THREAD

**Issue by lin-code-world** [dcloudio/uni-app#4881]
uniapp npm更新到3.0.0-4010420240430001 f12页面控制台报错
```
TypeError: Cannot read properties of null (reading '$el')
    at initElement (uni-h5.es.js:25546:45)
    at uni-h5.es.js:25554:5
    at vue.runtime.esm.js:4163:88
    at callWithErrorHandling (vue.runtime.esm.js:1381:19)
    at callWithAsyncErrorHandling (vue.runtime.esm.js:1388:17)
    at hook.__weh.hook.__weh (vue.runtime.esm.js:4141:19)
    at flushPostFlushCbs (vue.runtime.esm.js:1553:41)
    at flushJobs (vue.runtime.esm.js:1591:5)
```
``` javascript
function initElement() {
      refreshContainerElem = refreshRef.value.$el;   #指到这一行报错
      refreshControllerElem = refreshContainerElem.querySelector(".uni-page-refresh");
      refreshControllerElemStyle = refreshControllerElem.style;
      refreshInnerElemStyle = refreshControllerElem.querySelector(".uni-page-refresh-inner").style;
  }
```

**Comment by zhetengbiji** [comment]
已更新：3.0.0-4010420240430002
