### ISSUE TITLE
vue3下载nvue页面使用plus.webview.create创建网页后，网页中uni.postMessage会触发报错

### ISSUE THREAD

**Issue by Will-yc** [dcloudio/uni-app#4890]
vue3下载nvue页面使用plus.webview.create创建网页后，网页中uni.postMessage和uni.webView.postMessage都会触发报错，代码执行不下去,nvue页面的plus.globalEvent.addEventListener('plusMessage'也不会执行，以下是代码示例，
[vue3bug.zip](https://github.com/dcloudio/uni-app/files/15256748/vue3bug.zip)

**Comment by Will-yc** [comment]
报错信息

10:12:30.161 [JS Framework] Failed to execute the callback function:
 TypeError: Cannot read property 'nodeName' of undefined
10:12:30.166 reportJSException >>>> exception function:__WEEX_CALL_JAVASCRIPT__, exception:JavaScript execute error!Uncaught TypeError: Cannot read property 'nodeName' of undefined
 at Ud (uni-jsframework.js:44:225353)
 at tN (uni-jsframework.js:44:225528)
 at eI (uni-jsframework.js:44:242023)
 at QN (uni-jsframework.js:44:241935)
 at  (uni-jsframework.js:44:242660)
 at emit (uni-jsframework.js:23:11246)
 at subscribeHandler (uni-jsframework.js:44:45883)
 at pv (uni-jsframework.js:44:239270)
 at consume (uni-jsframework.js:23:15564)
 at callback (uni-jsframework.js:25:1659)
10:12:30.832 [JS Framework] Failed to execute the callback function:
 TypeError: Cannot read property 'nodeName' of undefined
