### ISSUE TITLE
scroll-view:  TypeError: Cannot read properties of null (reading 'scrollHeight'

### ISSUE THREAD

**Issue by gao-xiang** [dcloudio/uni-app#4904]
3.0.0-alpha-4010720240511003，scroll-view  有各种参数报错。

**Comment by Otto-J** [comment]
感谢反馈，你提到 vue3 的 scroll-view 运行有报错，可以补充案例和说明运行的平台吗，比如 android/ios/微信小程序还是 h5 ，补充更多信息，有助于定位和解决你的问题

**Comment by gao-xiang** [comment]
是在H5发现的，回退的上一个版本没在出现，有时是 scrollTop 未设置的报错，

**Comment by Otto-J** [comment]
你可以提供一个复现工程吗，只包含 scroll-view 的，我测试运行 hbuilderx 和 cli 看到控制台是正常的

**Comment by gao-xiang** [comment]
<scroll-view enable-back-to-top class="scroll-view" scroll-y>
      <slot />
    </scroll-view>

只要有以上代码就会出现，刷新后没有错误提示，在页面切换时会出现报错。

**Comment by Akun97** [comment]
> 你可以提供一个复现工程吗，只包含scroll-view的，我测试运行hbuilderx和cli看到控制台是正常的

Vue3 Ts CLI-3.0.0-4040520250104002  触发hmr update时，有scroll-view的页面会在控制台报错
`uni-h5.es.js:14318 Uncaught (in promise) TypeError: Cannot set properties of null (setting 'scrollLeft')
    at _scrollLeftChanged (uni-h5.es.js:14318:1)
    at uni-h5.es.js:14421:1`

<img width="1288" height="430" alt="Image" src="https://github.com/user-attachments/assets/9c2e9fc5-c36f-4d1d-95e3-3fbff07ac994" />
main.value还是指向旧的元素导致访问不到main.value相关属性
