### ISSUE TITLE
通过 vue-cli 创建的 typescript 项目，执行 yarn lint 报错。

### ISSUE THREAD

**Issue by simicn** [dcloudio/uni-app#496]
**问题描述**
通过 vue-cli 创建的 typescript 项目，执行 yarn lint 报错。

**复现步骤**
1.  创建项目`vue create -p dcloudio/uni-preset-vue uni-app`，选择 typescript 模板。
2. 在 package.json 中添加 lint script: 
```
"scripts": {
    "lint": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service lint"
}
...
```
3. 执行`yarn lint`

**预期结果**
正确进行[代码校验](https://vue-loader.vuejs.org/zh/guide/linting.html#eslint)

**实际结果**
执行`yarn lint`后报错
```
yarn lint                       
yarn run v1.7.0
$ cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service lint
 ERROR  TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:125:11)
    at Object.dirname (path.js:1260:5)
    at findConfigurationPath (.../uni-app/node_modules/tslint/lib/configuration.js:84:34)
    at Object.findConfiguration (.../uni-app/node_modules/tslint/lib/configuration.js:50:22)
    at lint (.../uni-app/node_modules/@vue/cli-plugin-typescript/lib/tslint.js:95:39)
    at api.registerCommand.args (.../uni-app/node_modules/@vue/cli-plugin-typescript/index.js:96:37)
    at Service.run (.../uni-app/node_modules/@vue/cli-service/lib/Service.js:221:12)
    at Object.<anonymous> (.../uni-app/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**系统信息:**
 - 操作系统
`macOS Mojave 10.14.5 `
 - uni-app版本
```
Environment Info:

  System:
    OS: macOS 10.14.5
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.7.0 - ~/.yarn/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.100
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @dcloudio/types: * => 0.2.3 
    @dcloudio/uni-app-plus: * => 0.0.247 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: * => 0.2.964 
    @dcloudio/uni-h5: * => 0.5.12 
    @dcloudio/uni-mp-alipay: * => 0.0.821 
    @dcloudio/uni-mp-baidu: * => 0.0.849 
    @dcloudio/uni-mp-qq: * => 0.0.105 
    @dcloudio/uni-mp-toutiao: * => 0.0.345 
    @dcloudio/uni-mp-weixin: * => 0.0.966 
    @dcloudio/uni-template-compiler: * => 0.9.179 
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.101 
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.483 
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: * => 0.2.846 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.8.0 
    @vue/babel-preset-jsx:  1.0.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.0.0 
    @vue/cli-overlay:  3.8.0 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-typescript: ^3.5.1 => 3.8.1 
    @vue/cli-service: ^3.0.4 => 3.8.4 
    @vue/cli-shared-utils:  3.8.0 
    @vue/component-compiler-utils:  2.6.0 
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0 
    @vue/eslint-config-typescript: ^4.0.0 => 4.0.0 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^5.2.3 => 5.2.3 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.10 => 2.6.10 
    vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
    vue-eslint-parser:  5.0.0 
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.0 
    vue-property-decorator: ^8.0.0 => 8.2.1 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by zhetengbiji** [comment]
使用 vue add @vue/eslint 安装
