### ISSUE TITLE
微信小程序中某个组件引用另一个组件时报错 [plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position xxx

### ISSUE THREAD

**Issue by xiaohe0601** [dcloudio/uni-app#4964]
> ComponentA

```vue
<template>
  <view class="component-a"></view>
</template>
```

> ComponentB

```vue
<template>
  <view class="component-b">
    <component-a></component-a>
  </view>
</template>

<script lang="ts" setup>
import ComponentA from "./ComponentA.vue";
</script>
```

> page

```vue
<template>
  <component-b></component-a>
</template>

<script lang="ts" setup>
import ComponentB from "./ComponentB.vue";
</script>
```

#### 报错信息

```shell
[plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position 87
at pages/index/index.vue:1:0
```

经测试，`3.0.0-4000820240401001` 版本正常，之后的版本都存在该问题

#### 版本信息
- uniapp：3.0.0-4010520240507001
- vue：3.4.27

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/4952

**Comment by Otto-J** [comment]
感谢反馈，如有问题请在 #4952
继续评论和回复。

**Comment by Tony-Code** [comment]
一样的问题，希望快点修复啊

**Comment by fxy060608** [comment]
最新的alpha已经修复，这是 @vitejs/plugin-vue@5.05 带来的兼容性问题

**Comment by dongjinc** [comment]
执行 npx @dcloudio/uvm 3.0.0-alpha-4020320240629001 这个版本就修复了

**Comment by wuxiaolan91** [comment]
是这个插件这个版本的问题: @vitejs/plugin-vue@5.05 ,我的是这个版本就无法引入自定义组件, 

我同事的版本是@vitejs/plugin-vue@5.04, 就没问题.

**Comment by neatstudio** [comment]
> 是这个插件这个版本的问题: @vitejs/plugin-vue@5.05 ,我的是这个版本就无法引入自定义组件,
> 
> 我同事的版本是@vitejs/plugin-vue@5.04, 就没问题.

类似，自动 升级后甚至无法watch，会一直报：
```bash
[plugin:commonjs] Transform failed with 1 error:
/Users/user/WebstormProjects/mini/src/App.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "lang"
at App.vue:1:8
  Expected ">" but found "lang"
  1  |  <script lang="ts" setup>
     |          ^
  2  |  import {onError, onHide, onLaunch, onShow} from "@dcloudio/uni-app";
  3  |  import {useAppStore} from "@/store/app";
   (x3)

```
降到5.0.4，并锁定，就完全 没问题了。
