### ISSUE TITLE
Vue3 项目安卓真机调试报错：Cannot read property '$page' of undefined

### ISSUE THREAD

**Issue by Sululu666** [dcloudio/uni-app#4973]
**问题描述**
运行到浏览器没有问题，运行到华为手机白屏

**复现步骤**
新建默认模版空项目，将index内容修改为我的项目展示内容后（插入了包含我的项目内容的组件），然后连接真机调试，看到报错，手机显示为白屏：

```
12:22:51.047 项目 'APPTest2' 编译成功。
12:22:51.059 ready in 8888ms.
12:22:51.077 正在建立手机连接...
12:22:51.288 手机端调试基座版本号为4.15, 版本号相同，跳过基座更新
12:22:52.930 正在同步手机端程序文件...
12:22:53.601 同步手机端程序文件完成
12:22:54.889 正在启动HBuilder调试基座...
12:22:55.974 应用【BimViewerAPPTest2】已启动
12:22:56.999 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property '$page' of undefined
 at Ea (uni-jsframework.js:44:35561)
 at exec (uni-jsframework.js:44:125339)
```

**预期结果**
正常运行

**实际结果**
白屏，且有报错

**系统信息:**
发行平台：安卓APP
操作系统：鸿蒙4.0.0
HBuilderX版本：HBuilderX.4.15.2024050802
uni-app版本 
设备信息：华为p40pro

**Comment by Otto-J** [comment]
需要简单判断一下，
问题一，默认的空模版运行到你的安卓设备有问题，其他安卓设备正常吗？
问题二，是否可以提供一个单页面代码，或者复现工程。提供更多信息，有助于定位和解答你的问题。

**Comment by Sululu666** [comment]
感谢回复，已经发现是使用uni的方法有误
