### ISSUE TITLE
【BUG】升级到最新版本发现input问题， input 组件 type="digit" 的时候，绑定的值如果是null，报错。之前版本无此问题。

### ISSUE THREAD

**Issue by zxhbloomer** [dcloudio/uni-app#5070]
升级前版本："@dcloudio/uni-app": "3.0.0-4000820240401001"
升级后版本："@dcloudio/uni-app": "3.0.0-4020420240722002"

升级到最新后，发现bug，升级前无此问题：
重现步骤：
1、input设置type="digit"
2、绑定值如果是null，报错：
main.ts?t=1722478657119:20 TypeError: Cannot read properties of null (reading 'toLocaleString')
at useCache (uni-h5.es.js:9799:60)
at setup (uni-h5.es.js:9847:17)
at callWithErrorHandling (vue.runtime.esm.js:1381:19)
at setupStatefulComponent (vue.runtime.esm.js:8930:25)
at setupComponent (vue.runtime.esm.js:8891:36)
at mountComponent (vue.runtime.esm.js:7218:7)
at processComponent (vue.runtime.esm.js:7184:9)
at patch (vue.runtime.esm.js:6650:11)
at mountChildren (vue.runtime.esm.js:6898:7)
at processFragment (vue.runtime.esm.js:7114:7)

![image](https://github.com/user-attachments/assets/3698d47d-dae7-429c-b69a-4873f88c66f3)

**Comment by bfc846958672** [comment]
https://github.com/dcloudio/uni-app/pull/5040  已经修复，下个版本上线

**Comment by zxhbloomer** [comment]
收到，那我关闭了。
