### ISSUE TITLE
突然断电闪退的问题后续会解决吗

### ISSUE THREAD

**Issue by kmq116** [dcloudio/uni-app#5073]
https://ask.dcloud.net.cn/question/162252
![image](https://github.com/user-attachments/assets/b7d4399d-2d20-41c0-ad61-b20848304bc3)
现象是，使用软件的过程中，设备没电关机了（突然断电），软件就没法使用了，停在启动页，然后会抓到错误日志
BOARD:tn0278_xwp_n3_zh16
BOOTLOADER:unknown
BRAND:P920-AN10
CPU_ABI:arm64-v8a
CPU_ABI2:
DEVICE:P920-AN10
DISPLAY:P920-AN10_ZH16_V04_20240729
FINGERPRINT:P920-AN10/P920-AN10/P920-AN10:12/SP1A.210812.016/1721812946:user/release-keys
HARDWARE:mt6833
HOST:zhengxb
ID:SP1A.210812.016
IS_DEBUGGABLE:false
IS_EMULATOR:false
MANUFACTURER:TYD
MODEL:P920-AN10
ODM_SKU:unknown
PERMISSIONS_REVIEW_REQUIRED:true
PRODUCT:P920-AN10
RADIO:unknown
SERIAL:unknown
SKU:unknown
SOC_MANUFACTURER:Mediatek
SOC_MODEL:MT6833V/ZA
SUPPORTED_32_BIT_ABIS:[Ljava.lang.String;@ab1edca
SUPPORTED_64_BIT_ABIS:[Ljava.lang.String;@871fb3b
SUPPORTED_ABIS:[Ljava.lang.String;@db62258
TAGS:release-keys
TIME:1722236577000
TYPE:user
UNKNOWN:unknown
USER:zhengxb
java.lang.IllegalArgumentException: Cannot parse iv:ciphertext:mac
	at io.dcloud.e.f.a$a.<init>(Unknown Source:16)
	at io.dcloud.e.f.b.b(Unknown Source:27)
	at io.dcloud.e.f.b.a(Unknown Source:28)
	at io.dcloud.common.adapter.util.SP.getsBundleData(Unknown Source:3)
	at io.dcloud.feature.gg.AolSplashUtil.getAL(Unknown Source:1)
	at io.dcloud.feature.gg.dcloud.ADHandler.pull(Unknown Source:55)
	at io.dcloud.feature.gg.dcloud.AolFeatureImpl.doForFeature(Unknown Source:141)
	at io.dcloud.feature.gg.AolFeatureImplMgr.doForFeature(Unknown Source:5)
	at io.dcloud.a.a(Unknown Source:16)
	at io.dcloud.b$a.run(Unknown Source:5)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7881)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:568)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

**Comment by kmq116** [comment]
https://ask.dcloud.net.cn/question/179037
同样的问题，我遇到的问题和他这边一样的
