### ISSUE TITLE
Error: wx.$$initRuntimeAutomator not exists

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#5102]
```
Error: wx.$$initRuntimeAutomator not exists
    at S.F.onMessage (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/@dcloudio+uni-mp-weixin@3.0.0-alpha-4000020240111001_postcss@8.4.38_vue@3.4.27/node_modules/@dcloudio/uni-mp-weixin/lib/uni.automator.js:1:1845)
    at S.emit (node:events:514:28)
    at WebSocket.<anonymous> (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/@dcloudio+uni-mp-weixin@3.0.0-alpha-4000020240111001_postcss@8.4.38_vue@3.4.27/node_modules/@dcloudio/uni-mp-weixin/lib/uni.automator.js:1:723)
    at callListener (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/websocket.js:1209:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:594:14)
    at Receiver.getData (/Users/mokevip/Documents/code/uni-egg-shell-man/node_modules/.pnpm/ws@8.17.0/node_modules/ws/lib/receiver.js:496:10)

Node.js v18.17.0
```

微信开发者工具版本号
[RC Build](https://developers.weixin.qq.com/miniprogram/dev/devtools/rc.html) (1.06.2407101)
    "@dcloudio/uni-automator": "3.0.0-alpha-4000020240111001"

**Comment by moke8** [comment]
![image](https://github.com/user-attachments/assets/a8518cb7-2c4c-4d69-abb4-3b0c1a113986)
排除了项目ts类型原因
