### ISSUE TITLE
通过符号链接引用node_modules中的自定义的未编译的vue单文件组件编译出错

### ISSUE THREAD

**Issue by linden5** [dcloudio/uni-app#513]
**问题描述**
通过**符号链接**从node_modules中引用自定义未编译的vue单文件组件时，编译出来的代码在**微信小程序**开发工具中报错

**复现步骤**
1.  在另一个项目文件夹中自定义一些vue单文件组件
2.  使用npm link或yarn link将该项目链接到uni-app工程目录
3.  在uni-app工程的代码中引用这些组件
4.  启动微信小程序开发服务器dev:mp-weixin
5.  在微信小程序开发工具中查看实际效果

引用代码：
```
<template>
  <my-component/>
</template>
<script>
import MyComponent from 'my-package/src/my-component'

export default {
  components: {
    MyComponent
  }
}
</script>
```

**预期结果**
1. 编译通过
2. 微信小程序开发工具中无报错

**实际结果**
1. 编译通过
2. 微信小程序开发工具报错：

```
VM54:1 jsEnginScriptError
Component is not found in path "app/my-package/src/my-component" (using by "pages/my-page/index");onAppRoute
Error: Component is not found in path "app/my-package/src/my-component" (using by "pages/my-page/index")
    at m (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:944277)
    at m (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:944463)
    at http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:961690
    at Object.t.addView (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:962236)
    at Function.value (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1041611)
    at kt (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1055700)
    at http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1057659
    at Tt (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1057689)
    at Function.<anonymous> (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1062461)
    at i.<anonymous> (http://127.0.0.1:15980/appservice/__dev__/WAService.js:1:1034791)
```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Windows 10
 - HBuilderX版本: 未使用HBuilderX
 - uni-app版本:

```
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz
  Binaries:
    Node: 10.16.0 - D:\Programs\nodejs\node.EXE
    Yarn: 1.16.0 - D:\Programs\nodejs\yarn.CMD
    npm: 6.9.0 - D:\Programs\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.247
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.966
    @dcloudio/uni-h5: * => 0.5.12 (0.4.9)
    @dcloudio/uni-mp-alipay: * => 0.0.821
    @dcloudio/uni-mp-baidu: * => 0.0.849 (0.0.812)
    @dcloudio/uni-mp-qq: * => 0.0.105
    @dcloudio/uni-mp-toutiao: * => 0.0.345 (0.0.312)
    @dcloudio/uni-mp-weixin: * => 0.0.966 (0.0.912)
    @dcloudio/uni-template-compiler: * => 0.9.179
    @dcloudio/uni-ui: ^0.0.8 => 0.0.8
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.102
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.483
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.846
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.8.0 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-i18n: ^8.11.2 => 8.11.2
    vue-lazyload:  1.2.6
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```

 - 设备信息: 未使用真机

**补充信息**
1. 报错中提到了找不到`app/my-package/src/my-component`，该app文件夹确实没有出现在`项目根目录/dist/dev/mp-weixin`下，而是直接输出到了项目根目录下面
2. 把该文件夹手动移动到正确的位置，又会提示类似的错误，这次找不到的是my-component引用的sub-component。去对应的文件夹下面查看，发现sub-component只生成了一个js和wxml，缺少json和wxss文件

**Comment by linden5** [comment]
经过调试，发现该问题是由于文件解析引起的，设置[webpack resolve.symlinks](https://webpack.js.org/configuration/resolve/#resolvesymlinks)为false可解决该问题。

**Comment by jwhklk** [comment]
> 经过调试，发现该问题是由于文件解析引起的，设置[webpack resolve.symlinks](https://webpack.js.org/configuration/resolve/#resolvesymlinks)为false可解决该问题。
> 
> 相关问题：[kaola-fed/megalo#279](https://github.com/kaola-fed/megalo/issues/279)

在哪里设置

**Comment by linden5** [comment]
在vue.config.js中设置，参考[vue-cli 3文档](https://cli.vuejs.org/guide/webpack.html#working-with-webpack)，类似下面这样
```
  chainWebpack(config) {
    config.resolve.symlinks(false)
  }
```

**Comment by cat-walk** [comment]
> 在vue.config.js中设置，参考[vue-cli 3文档](https://cli.vuejs.org/guide/webpack.html#working-with-webpack)，类似下面这样
> 
> ```
>   chainWebpack(config) {
>     config.resolve.symlinks(false)
>   }
> ```

遇到了类似的问题，用这个方法解决了，十分感谢🙏
