### ISSUE TITLE
自定义组件模式 bug

### ISSUE THREAD

**Issue by ThomasGuoItaly** [dcloudio/uni-app#604]
老项目 切换至 新自定义组件模式，后报错:
项目中无 charAt 变量，编译器没有提示 出错的地方，如何查看 是哪里出错????
```
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
TypeError: Cannot read property 'charAt' of undefined
10:28:24.044     at parseEvent (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\data\event.js:181:20)
10:28:24.076     at _processEvent (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\data\event.js:328:9)
10:28:24.102     at processEvent (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\data\event.js:387:5)
10:28:24.103     at processes.forEach.process (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\data\index.js:34:5)
10:28:24.113     at Array.forEach (<anonymous>)
10:28:24.113     at traverseData (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\data\index.js:33:13)
10:28:24.113     at Object.CallExpression (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\lib\script\traverse\visitor.js:165:56)
10:28:24.113     at NodePath._call (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\path\context.js:53:20)
10:28:24.128     at NodePath.call (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\path\context.js:40:17)
10:28:24.128     at NodePath.visit (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\path\context.js:88:12)
10:28:24.144     at TraversalContext.visitQueue (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\context.js:118:16)
10:28:24.144     at TraversalContext.visitSingle (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\context.js:90:19)
10:28:24.159     at TraversalContext.visit (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\context.js:146:19)
10:28:24.159     at Function.traverse.node (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\index.js:94:17)
10:28:24.175     at NodePath.visit (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\path\context.js:95:18)
10:28:24.175     at TraversalContext.visitQueue (C:\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\uni-template-compiler\node_modules\@babel\traverse\lib\context.js:118:16)
```

**Comment by hbcui1984** [comment]
建议升级到最新版验证，如果问题依旧，可以上传可重现问题的demo
