### ISSUE TITLE
打包 qq 小程序报错

### ISSUE THREAD

**Issue by imaxing** [dcloudio/uni-app#910]
**问题描述**
[问题描述：qq 小程序 yarn dev:mp-qq yarn build:mp-qq 报错]

**复现步骤**

1.  yarn dev:mp-qq || yarn build:mp-qq
```
error  in ./src/pages.json

Module build failed (from ./node_modules/@dcloudio/webpack-uni-pages-loader/lib/index.js):
TypeError: Cannot read property 'content' of undefined
    at module.exports (/Users/mac/Desktop/iluoy/lucky-lele/node_modules/@dcloudio/webpack-uni-pages-loader/lib/platforms/mp-qq/index.js:10:11)
    at Object.module.exports (/Users/mac/Desktop/iluoy/lucky-lele/node_modules/@dcloudio/webpack-uni-pages-loader/lib/index-new.js:67:71)
    at Object.module.exports (/Users/mac/Desktop/iluoy/lucky-lele/node_modules/@dcloudio/webpack-uni-pages-loader/lib/index.js:45:35)

 @ ./src/main.js?{"page":"pages%2Findex%2Findex"} 3:0-20
```

**预期结果**
运行 qq 小程序正常

**实际结果**
![image](https://user-images.githubusercontent.com/26427785/67631125-01946f80-f8cd-11e9-8551-faa80483f75c.png)

**系统信息:**
 - 发行平台: qq 小程序
 - uni-app版本 
   ```
      uni-app v2.3.3
      uni-app cli v2.0.0-23320190923002
   ```

**补充信息**

```json
// pages.json
{
	"pages": [
		{
			"path": "pages/index/index",
			"style": {
				"navigationBarTitleText": "幸运乐乐"
			}
		}
	],
	"globalStyle": {
		"navigationBarTextStyle": "black",
		"navigationBarTitleText": "xxxxxx",
		"navigationBarBackgroundColor": "#F8F8F8",
		"backgroundColor": "#F8F8F8"
	},
	"tabBar": {
    "color": "#7A7E83",
    "selectedColor": "#3cc51f",
    "borderStyle": "black",
		"backgroundColor": "#ffffff",
    "list": [
			{
        "pagePath": "pages/index/index",
        "iconPath": "static/icons/lottery.png",
        "selectedIconPath": "static/icons/lottery-selected.png",
        "text": " 幸运抽奖"
			}, 
			{
					"pagePath": "pages/conversion/conversion",
					"iconPath": "static/icons/conversion.png",
					"selectedIconPath": "static/icons/conversion-selected.png",
					"text": "积分兑换"
			},
			{
					"pagePath": "pages/user/user",
					"iconPath": "static/icons/user.png",
					"selectedIconPath": "static/icons/user-selected.png",
					"text": "我的"
			}
		]
	}
}

```

**Comment by javascriptchen** [comment]
Cannot read property 'content' of undefined。
检查一下你的代码里哪里有用content，但是没有赋值

**Comment by imaxing** [comment]
@javascriptchen content 是 node_modules 包里面报的错误

**Comment by javascriptchen** [comment]
发可复现的代码，这样看不出来

**Comment by imaxing** [comment]
@javascriptchen 

这个没有特定代码 我build:mp-weixin 是正常的
![image](https://user-images.githubusercontent.com/26427785/67834736-284be380-fb23-11e9-9ad8-377c5f9e39a0.png)


### log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/mac/.nvm/versions/node/v10.13.0/bin/node',
1 verbose cli   '/Users/mac/.nvm/versions/node/v10.13.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build:mp-qq' ]
2 info using npm@6.11.3
3 info using node@v10.13.0
4 verbose run-script [ 'prebuild:mp-qq', 'build:mp-qq', 'postbuild:mp-qq' ]
5 info lifecycle luckey-lele@0.1.0~prebuild:mp-qq: luckey-lele@0.1.0
6 info lifecycle luckey-lele@0.1.0~build:mp-qq: luckey-lele@0.1.0
7 verbose lifecycle luckey-lele@0.1.0~build:mp-qq: unsafe-perm in lifecycle true
8 verbose lifecycle luckey-lele@0.1.0~build:mp-qq: PATH: /Users/mac/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mac/Desktop/iluoy/lucky-lele/node_modules/.bin:/Users/mac/.nvm/versions/node/v10.13.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
9 verbose lifecycle luckey-lele@0.1.0~build:mp-qq: CWD: /Users/mac/Desktop/iluoy/lucky-lele
10 silly lifecycle luckey-lele@0.1.0~build:mp-qq: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build' ]
11 silly lifecycle luckey-lele@0.1.0~build:mp-qq: Returned: code: 1  signal: null
12 info lifecycle luckey-lele@0.1.0~build:mp-qq: Failed to exec build:mp-qq script
13 verbose stack Error: luckey-lele@0.1.0 build:mp-qq: `cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/Users/mac/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/Users/mac/.nvm/versions/node/v10.13.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
14 verbose pkgid luckey-lele@0.1.0
15 verbose cwd /Users/mac/Desktop/iluoy/lucky-lele
16 verbose Darwin 17.5.0
17 verbose argv "/Users/mac/.nvm/versions/node/v10.13.0/bin/node" "/Users/mac/.nvm/versions/node/v10.13.0/bin/npm" "run" "build:mp-qq"
18 verbose node v10.13.0
19 verbose npm  v6.11.3
20 error code ELIFECYCLE
21 error errno 1
22 error luckey-lele@0.1.0 build:mp-qq: `cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build`
22 error Exit status 1
23 error Failed at the luckey-lele@0.1.0 build:mp-qq script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by imaxing** [comment]
#### 自己试着找了找问题
**首先是报错**
![报错](https://user-images.githubusercontent.com/26427785/67631125-01946f80-f8cd-11e9-8551-faa80483f75c.png)

> 报错文件是 `/node_modules/@dcloudio/webpack-uni-pages-loader/lib/platforms/mp-qq/index.js`
> 报错内容为 `project is undefined`, 所以 content 找不到

**打开mp-qq/index.js, project 是从 mp.js 导入的**
![image](https://user-images.githubusercontent.com/26427785/68183201-9fc3bc00-ffd6-11e9-8759-d3637621ffa5.png)


> project 数据是从 `node_modules/@dcloudio/webpack-uni-pages-loader/lib/platforms/mp.js`文件引入的, 经过断点测试找到在下图地方 return 出来的结果, 但是 return 的结果中 并没有 project 对象

![image](https://user-images.githubusercontent.com/26427785/68183228-ba963080-ffd6-11e9-9425-50f28339a605.png)

请官方尽快检查, 是否是代码错误, 如若是麻烦尽快修改 
如果不是还请指明这bug 问题会出在哪? 谢谢 🙏
@javascriptchen

**Comment by javascriptchen** [comment]
你如果在HBuilderX里面直接打包呢，会不会还有报错？
