### ISSUE TITLE
nvue中templateLoader报错TypeError: value.trim is not a function是什么原因

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#935]
```
Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-uni-nvue-loader/lib/templateLoader.js):
20:59:47.625 TypeError: value.trim is not a function
20:59:47.633     at addHandler (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:1201:48)
20:59:47.635     at processAttrs (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:2133:9)
20:59:47.646     at processElement (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:1737:3)
20:59:47.646     at closeElement (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:1391:17)
20:59:47.657     at Object.end (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:1595:7)
20:59:47.658     at parseEndTag (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:531:19)
20:59:47.674     at parseHTML (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:347:11)
20:59:47.691     at parse (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:1479:3)
20:59:47.691     at baseCompile (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:4386:13)
20:59:47.707     at Object.compile (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:4361:22)
20:59:47.709     at compile (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/weex-template-compiler/build.js:5031:25)
20:59:47.738     at actuallyCompile (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-uni-nvue-loader/lib/compileTemplate.js:69:84)
20:59:47.739     at compileTemplate (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-uni-nvue-loader/lib/compileTemplate.js:31:16)
20:59:47.758     at Object.module.exports (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-uni-nvue-loader/lib/templateLoader.js:46:20)
```

我现在nvue页面出现了一个错误，编译到mp/h5倒是没有出现错误。想定位错误，但是给出的错误代码应该是模块加载的问题，也不知道到底是哪个地方没有对上。

请求一下。

我是picker-view以及picker-column。

**Comment by javascriptchen** [comment]
只有字符串才有trim方法，你是不是数字啊？

**Comment by wakaryry** [comment]
我瞅瞅。主要是现在我也不好定位我里面哪里的问题。主要是想看看有没有什么别的提示，方便定位错误的。

**Comment by wakaryry** [comment]
解决了。主要是 代码里面有一个 `@touchmove.stop.prevent catchtouchmove="true"` 这玩意。写成 `@touchmove.stop.prevent="()=>{}"` 这个就好了。
